In [2]:
import pandas as pd
from konlpy.tag import Okt
import numpy as np
import gensim.corpora as corpora
import re
import gensim
from pprint import pprint

In [165]:
df = pd.read_csv('find.csv')
df.head()
len(df)

16708

In [290]:
drop_df = df.drop_duplicates(keep='first')
len(drop_df)

15129

In [291]:
drop_df['href'].fillna(method='ffill',inplace=True)
drop_df['title'].fillna(method='ffill',inplace=True)
drop_df['reviewNum'].fillna(method='ffill',inplace=True)
drop_df['tag'].fillna(method='ffill',inplace=True)
drop_df['brand'].fillna(method='ffill',inplace=True)
drop_df['company'].fillna(method='ffill',inplace=True)
drop_df['howToUse'].fillna(method='ffill',inplace=True)
drop_df['ingredients'].fillna(method='ffill',inplace=True)
drop_df['image'].fillna(method='ffill',inplace=True)
drop_df['volume'].fillna(method='ffill',inplace=True)
drop_df['price'].fillna(method='ffill',inplace=True)
# drop_df = drop_df[drop_df['tag'].apply(lambda x: str(x) == '두피샴푸' or str(x) == '탈모샴푸')]
drop_df

/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/762488147.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  drop_df['href'].fillna(method='ffill',inplace=True)
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/762488147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drop_df['href'].fillna(method='ffill',inplace=True)
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/762488147.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  drop_df['title'].fillna(method='ffill',inplace=True)
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/762488147.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drop_df['title'].fillna(method='ffill',inplace=True)
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/762488147.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  drop_df['reviewNum'].fillna(method='ffill',inplace=True)
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/762488147.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drop_df['reviewNum'].fillna(method='ffill',inplace=True)
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/762488147.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  drop_df['tag'].fillna(method='ffill',inplace=True)
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/762488147.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drop_df['tag'].fillna(method='ffill',inplace=True)
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/762488147.py:5: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  drop_df['brand'].fillna(method='ffill',inplace=True)
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/762488147.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drop_df['brand'].fillna(method='ffill',inplace=True)
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/762488147.py:6: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  drop_df['company'].fillna(method='ffill',inplace=True)
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/762488147.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drop_df['company'].fillna(method='ffill',inplace=True)
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/762488147.py:7: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  drop_df['howToUse'].fillna(method='ffill',inplace=True)
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/762488147.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drop_df['howToUse'].fillna(method='ffill',inplace=True)
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/762488147.py:8: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  drop_df['ingredients'].fillna(method='ffill',inplace=True)
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/762488147.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drop_df['ingredients'].fillna(method='ffill',inplace=True)
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/762488147.py:9: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  drop_df['image'].fillna(method='ffill',inplace=True)
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/762488147.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drop_df['image'].fillna(method='ffill',inplace=True)
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/762488147.py:10: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  drop_df['volume'].fillna(method='ffill',inplace=True)
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/762488147.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drop_df['volume'].fillna(method='ffill',inplace=True)
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/762488147.py:11: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  drop_df['price'].fillna(method='ffill',inplace=True)
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/762488147.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drop_df['price'].fillna(method='ffill',inplace=True)

,href,title,reviewNum,tag,brand,company,howToUse,ingredients,image,volume,price,totalScore,satisfactionScore,priceScore,rebuyScore,commenter,commentDate,commentContent,commentGood,commentBad
0,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,"41,500원",NaN,80%,80%,100%,K2646350517,3달 전,NaN,"앞머리 모발이식 13년전에 하고는 프로스카 띄엄띄엄 먹었는데, 정수리 광탈 시작...","스댕 용기 개 이쁘고 좋은데, 원가 너무 비싸서 내가 보기에는 가격이 높은 최대 ..."
1,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,"41,500원",100%,NaN,NaN,NaN,a337*****,한 시간 전,탈모라 써봤는데 시원하고 좋아요,NaN,NaN
2,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,"41,500원",100%,NaN,NaN,NaN,suwo******,하루 전,머리감을때마다 시원하고좋아요,NaN,NaN
3,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,"41,500원",100%,NaN,NaN,NaN,wall***,하루 전,전에 쿨샴푸를 한번썻는데 맘에들어서 다른색으로 하나 더 주문했습니다. 샘플 사은품...,NaN,NaN
4,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,"41,500원",100%,NaN,NaN,NaN,zzzz****,2일 전,아주좋습니다좋아요~,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16703,https://daedamo.com/ingre/99?sca=탈모관련상품&overla...,\n 니심 건성모발용 샴푸,0.0,두피샴푸,니심,니옥신,두피와 모발 전체를 마사지 하듯이 1분가량 꼼꼼하게 샴푸하고 미온수로 씻어냅니다. ...,"정제수, 소듐C14-16올레핀설포네이트, 소듐코코암포아세테이트, 피이지-4레이프씨다...",https://daedamo.com/new/data/file/ingre/179434...,240ml,"36,000원",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16704,https://daedamo.com/ingre/82?sca=탈모관련상품&overla...,\n 트리코민 덴시파잉 샴푸,0.0,두피샴푸,트리코민,니옥신,거품을 충분히 내신 후 바로 헹구지 마시고 3-5분 가량 그대로 두어 영양성분이 충...,"정제수, 알로에베라잎즙, 에키네시하추출물, 아이소말트, 완두싹추출물, 하이드롤라이즈...",https://daedamo.com/new/data/file/ingre/179434...,177.4ml,"39,800원",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16705,https://daedamo.com/ingre/80?sca=탈모관련상품&overla...,\n 드림헤어 순간증모제 전용 미스트,0.0,스타일링,드림헤어,니옥신,증모제를 사용하신후 본 제품을 직접적으로 분사하지 마시고 머리위 하늘에 뿌려주듯 분...,"에탄올, 정제수, 아크릴레이트/옥틸아크릴아마이드코폴리머, 녹차추출물, 곰솔잎추출물,...",https://daedamo.com/new/data/file/ingre/179434...,150ml,"8,000원",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16706,https://daedamo.com/ingre/75?sca=탈모관련상품&overla...,\n 드림헤어 블랙시크릿(휴대용),0.0,헤어커버,드림헤어,니옥신,증모제를 도포후 두피쪽에 증착될 수 있도록 머리를 쓰다듬듯이 살살 털어줍니다.,"레이온, 폴라아마이드, 비오틴, 실크펩타이드, 카퍼트리펩타이드, 대두레시틴, 헤나추출물",https://daedamo.com/new/data/file/ingre/179434...,7g,"15,000원",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16707,https://daedamo.com/ingre/74?sca=탈모관련상품&overla...,\n 드림헤어 순간증모제,0.0,헤어커버,드림헤어,니옥신,증모제를 도포후 두피쪽에 증착될 수 있도록 머리를 쓰다듬듯이 살살 털어줍니다.,"레이온, 폴리아마이드, 비오틴, 실크펩타이드, 카퍼트리펩타이드, 대두레시틴, 헤나추출물",https://daedamo.com/new/data/file/ingre/179434...,23g,"35,000원",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [169]:
# df = drop_df
# df.nunique()
len(drop_df)

12168

In [170]:
content = drop_df[drop_df['commentContent'].notnull()]['commentContent']
good = drop_df[drop_df['commentGood'].notnull()]['commentGood']
bad = drop_df[drop_df['commentBad'].notnull()]['commentBad']
print(len(content),len(good),len(bad))
content

916 9874 5739

1                                      탈모라 써봤는데 시원하고 좋아요
2                                        머리감을때마다 시원하고좋아요
3        전에 쿨샴푸를 한번썻는데 맘에들어서 다른색으로 하나 더 주문했습니다. 샘플 사은품...
4                                        아주좋습니다좋아요~
5            향이 진하게 나고 시원한 감이 있어서 좋아요 거품 밀도도 좋고요
                              ...
1171                                         감사합니다 번창하세오
1172     배송이빠르게와서 한번이용해보았습니다괜찮아서 앞으로도 계속구매해볼까생각중입니다
1173     쿠팡으로 사서 써보고 좋아서 부모님댁에도주문해드렸어요.제가 10년째 탈모샴푸를 쓰...
1174     거품이 신기하고 시원한 탈모샴푸가 궁금해서 구매했는데 와 평소에 없던 비듬이 생겨...
1175     거품도 풍성하게 나고 머릿결도 좋아진 것 같아요꾸준히 쓰면 모발에 힘도 나겠죠? ...
Name: commentContent, Length: 916, dtype: object

In [76]:
tokenizer = Okt()

In [171]:
pattern = re.compile(r'[\n\t]+')
def make_tokens(doc):
    tokens = []
    if doc and (type(doc)==str or not np.isnan(doc)):
        cleaned_doc = pattern.sub(' ',doc).strip()
        phrase = tokenizer.pos(cleaned_doc,norm=True,stem=True)
        tokens = [word[0] for word in phrase if word[0] and (word[1] in ['Noun','Adjective','Verb','Adverb','VerbPrefix','Suffix'] and (word[0] not in ['하다','있다']))]
    return tokens

In [172]:
cont_tokens = []
for t in content:
    cont_tokens.append(make_tokens(t))
cont_tokens

[['탈모', '써다', '보다', '시원하다', '좋다'],
 ['머리', '감', '때', '시원하다', '좋다'],
 ['전',
  '쿨',
  '샴푸',
  '한번',
  '썻',
  '늘다',
  '맘',
  '들어서다',
  '색',
  '하나',
  '더',
  '주문',
  '샘플',
  '사은',
  '품다',
  '정말',
  '좋다',
  '여'],
 ['아주', '좋다', '좋다'],
 ['향', '진하다', '나다', '시원하다', '감', '좋다', '거품', '밀도', '좋다'],
 ['맨솔',
  '약하다',
  '좋다',
  '통',
  '문제',
  '건지다',
  '샴푸',
  '스물',
  '스물',
  '입구',
  '나오다',
  '빼다',
  '좋다'],
 ['테', '안', '맞다'],
 ['강력하다',
  '쿨링',
  '샴푸',
  '원하다',
  '구입',
  '쿨링',
  '감다',
  '강하다',
  '않다',
  '탄산',
  '땜',
  '더',
  '강하다',
  '생각',
  '생각',
  '약하다',
  '정력',
  '좋다',
  '머리',
  '결',
  '부드럽다',
  '맘',
  '드네'],
 ['좋다', '빨르다', '재', '구매', '최고', '감사'],
 ['시원하다', '부드럽다'],
 ['통째', '쓰다', '중', '이다', '크다', '단점', '없다', '샴푸', '무난', '쓰기', '좋다'],
 ['빠르다', '배송', '감사하다'],
 ['탈모', '효과', '같다', '시원하다'],
 ['자다', '쓰다', '통째', '두피', '시원하다'],
 ['샴푸', '비다', '시원하다', '좋다'],
 ['샴푸', '비다', '많이', '시원하다', '좋다', '여'],
 ['멏년',
  '동안',
  '안',
  '써다',
  '보다',
  '삼',
  '푸다',
  '들이다',
  '없다',
  '해외',
  '직구',
  '비싸다',
  '제품',
  '들',
  '들다',
  '골고루',
  '써다',
  '보다',
  '이제',
  '서다',
  '찾다',
  '같다',
  '한시름',
  '덜다'],
 ['사용', '때', '두피', '시원하다', '느낌', '자다', '사용', '중', '이다'],
 ['다',
  '은데',
  '좀',
  '지저분하다',
  '써다',
  '용',
  '샴푸',
  '쓰다',
  '펌프',
  '부분',
  '늘',
  '거품',
  '왕창',
  '붙다',
  '샴푸',
  '몸통',
  '쌓이다'],
 ['올여름', '이', '샴푸', '나', '머리털', '케어', '해주다'],
 ['아직', '은', '모르다', '좀더', '써다', '보다'],
 ['시원하다', '두피', '감', '떨어지다'],
 ['번째', '구매', '이다', '남편', '두피', '시원하다', '정력', '좋다', '좋아하다'],
 ['정력',
  '보통',
  '듯',
  '하',
  '고요',
  '탈모',
  '효과',
  '좀더',
  '써다',
  '보다',
  '되다',
  '요',
  '자꾸',
  '펌핑',
  '뒤',
  '질질',
  '흘러내리다',
  '좀',
  '지저분하다',
  '아쉽다'],
 ['시원하다', '자다', '감다', '좋다'],
 ['드디어', '좋다', '샴푸', '찾다', '탄산', '거품', '그렇다', '사용', '후', '보이다'],
 ['달',
  '째',
  '사용',
  '머리',
  '빠지다',
  '효과',
  '모르다',
  '더',
  '빠지다',
  '같다',
  '재다',
  '의사',
  '없다'],
 ['아주', '좋다', '포장', '깔끔하다', '오다', '자다', '쓰다'],
 ['두피', '시원하다', '개운하다'],
 ['두피',
  '시원하다',
  '열',
  '내리다',
  '느낌',
  '들다',
  '두피',
  '효과',
  '기대',
  '해보다',
  '탈모',
  '좋다',
  '듯'],
 ['감다', '시원하다', '좋다'],
 ['두피', '엄청', '시원하다', '느낌', '이'],
 ['엄청', '시원하다', '좋다'],
 ['배송',
  '진짜',
  '빨르다',
  '신랑',
  '꺼',
  '써다',
  '보다',
  '좋다',
  '또',
  '구매',
  '린스',
  '안해',
  '부드럽다'],
 ['두피', '건조하다', '삭제', '모발', '모발'],
 ['샴푸', '너무', '시원하다', '상쾌하다', '만족하다'],
 ['배송', '빠르다', '시원하다'],
 ['처음', '써다', '보다', '가성', '비', '좋다', '깔끔하다'],
 ['머리', '아주', '시원하다', '너무', '좋다'],
 ['거품', '신기하다', '머리', '감고', '나다', '개운하다'],
 ['광고', '보고', '구매', '두피', '별로', '시원하다', '않다', '도로', '광고', '과장', '광고인', '듯'],
 ['사용',
  '해봤다',
  '정력',
  '샴푸',
  '후',
  '트린트먼트',
  '사용',
  '정도',
  '데',
  '일리',
  '사용',
  '테',
  '아니다',
  '같다'],
 ['광고', '보고', '구매', '생각', '엄청', '쿨링감', '아니다', '쫀쫀하', '정력', '좋다'],
 ['너무', '시원하다', '좋다', '베스트', '샴프', '굿'],
 ['시원하다', '이', '탈모', '방지', '효과', '아직', '모르다'],
 ['시원하다', '좋다', '사용', '후', '삼', '푸다', '입구', '삼퓨', '질질', '세다'],
 ['머리', '시원하다', '좋다'],
 ['시원하다', '좋다'],
 ['재다', '여름', '아주', '좋다', '것', '같다'],
 ['만족', '사용', '중', '이다'],
 ['어느',
  '정도',
  '흠',
  '잡히다',
  '찌다',
  '지성',
  '분',
  '들',
  '번은',
  '써다',
  '것',
  '같다',
  '사용',
  '후',
  '계속',
  '제품',
  '나오다',
  '거품',
  '생기다',
  '부분',
  '좀',
  '불편하다'],
 ['두피', '엄첫', '시원하다'],
 ['정력', '좋다', '탈모', '도움', '되다', '자다', '모르다'],
 ['거품',
  '자다',
  '나다',
  '깨끗하다',
  '자다',
  '씻기다',
  '효과',
  '더',
  '써다',
  '보다',
  '알다',
  '향',
  '좋다',
  '체적',
  '만족하다'],
 ['지루', '성', '두피', '염', '분', '들', '거', '꼭', '쓸다'],
 ['이전', '쓰다', '쿨', '딥', '다', '써다', '새롭다', '또', '주문', '잘쓰다'],
 ['통째', '구매', '이다', '여름', '진짜', '이만', '샴푸', '없다', '같다'],
 ['엄청', '시원하다', '여름', '쓰기', '정말', '좋다'],
 ['좋다', '좋다', '좋다', '좋다', '좋다', '좋다', '좋다', '좋다'],
 ['시원하다'],
 ['신랑', '꾸준하다', '사용', '신랑', '좋다'],
 ['만족하다', '많이', '파다'],
 ['쿨링감', '끝내주다'],
 ['정력', '시원하다', '넘다', '좋다'],
 ['좋다', '두피', '좋다'],
 ['배송', '빠르다', '약하다', '쿨하다', '느낌', '정력', '좋다', '듯해'],
 ['탈모', '시원하다', '되어다', '기분', '좋다', '쓰다'],
 ['배송',
  '빠르다',
  '포장',
  '꼼꼼하다',
  '샴푸',
  '한번',
  '사용',
  '해봤다',
  '시원하다',
  '맘',
  '듭니',
  '꾸다',
  '준',
  '사용',
  '해보다',
  '후기',
  '다시',
  '올리다'],
 ['배송', '빨', '리오네', '포장', '신경', '써주다', '믿음', '가다', '꾸준하다', '써다', '보다'],
 ['오늘',
  '받다',
  '보고',
  '바로',
  '써다',
  '보다',
  '거품',
  '좋다',
  '두피',
  '시원하다',
  '탈모',
  '완화',
  '좀더',
  '써다',
  '보다'],
 ['빨리', '자다', '도착', '확실하다', '종전', '머리카락', '덜', '빠지다'],
 ['진짜',
  '뻥',
  '안치',
  '머리카락',
  '빠지다',
  '확실하다',
  '줄다',
  '계속',
  '것',
  '쓸다',
  '생각',
  '리',
  '당분간'],
 ['탈모',
  '양모',
  '자다',
  '모르다',
  '정은',
  '좋다',
  '편',
  '아침',
  '다른',
  '샴푸',
  '저녁',
  '퇴근',
  '후',
  '이',
  '녀석',
  '사용',
  '중'],
 ['정말', '시원하다', '탈모', '효과', '모르다', '정력', '매우', '만족하다'],
 ['시원하다', '쿨링', '감다', '좋다', '거품', '풍부하다'],
 ['샴푸',
  '너무',
  '좋다',
  '요',
  '벌써',
  '다',
  '써다',
  '재다',
  '근데',
  '펌핑',
  '나다',
  '조금씩',
  '흘러나오다',
  '샴푸',
  '몸통',
  '묻다',
  '굳다',
  '그래도',
  '좋다'],
 ['거품', '자다', '사용', '편하다'],
 ['테', '각질', '생기다'],
 ['처음',
  '파랑색',
  '통',
  '써다',
  '보고',
  '맘',
  '들다',
  '이번',
  '연두색',
  '구매',
  '두피',
  '어떻다',
  '모르다',
  '머리',
  '감다',
  '빠지다',
  '머리카락',
  '좀',
  '줄어들다',
  '같다',
  '해',
  '다',
  '좋다',
  '탄산',
  '때문',
  '잔',
  '여물',
  '떨어지다',
  '통',
  '지저분하다',
  '지다',
  '불편하다'],
 ['남편',
  '머리',
  '열도',
  '많다',
  '탈모',
  '좀',
  '빨리',
  '오다',
  '주문',
  '해봤다',
  '열도',
  '낮추다',
  '시원하다',
  '좋다',
  '계속',
  '보',
  '더',
  '좋아지다'],
 ['배송', '빠르다', '달', '후기', '남다'],
 ['탈모',
  '방지',
  '샴푸',
  '게',
  '단기간',
  '효과',
  '알다',
  '없다',
  '장기간',
  '써다',
  '보다',
  '알다',
  '같다'],
 ['진짜', '계속계속', '쓸다', '가격', '조금', '더', '낮다', '최고'],
 ['우연히',
  '유투브',
  '알',
  '되어다',
  '써다',
  '보다',
  '저',
  '고민',
  '거리',
  '많이',
  '해결',
  '준',
  '것',
  '같다',
  '두피',
  '지성',
  '그렇다',
  '두피',
  '뾰루지',
  '많이',
  '나다',
  '가렵',
  '그렇다',
  '증상',
  '많이',
  '사라지다',
  '여전하다',
  '아침',
  '이',
  '기름',
  '올라오다',
  '평소',
  '가렵',
  '않다',
  '너무',
  '좋다',
  '뾰루지',
  '훨',
  '씬',
  '덜',
  '달',
  '반정',
  '계속',
  '쓰다',
  '너무',
  '맘',
  '들어서다',
  '마침',
  '라이브',
  '쇼핑',
  '더',
  '구입',
  '좋다',
  '가격',
  '구입',
  '좋다',
  '샘플',
  '감사'],
 ['배송',
  '빠르다',
  '오다',
  '사용',
  '한지',
  '며칠',
  '안되다',
  '탈모',
  '케어',
  '효과',
  '아직',
  '모르다',
  '꾸준하다',
  '써다',
  '보다',
  '쿨',
  '고민',
  '사다',
  '좋다',
  '거',
  '같다',
  '사은',
  '품',
  '같이',
  '준',
  '쿨',
  '써다',
  '보고',
  '더',
  '만족하다',
  '나중',
  '구매',
  '겠다',
  '개',
  '써다',
  '보다',
  '기회',
  '되다',
  '넘다',
  '좋다'],
 ['배송', '빠르다', '만족하다'],
 ['가려움', '없다', '무조'],
 ['달', '사용', '해보다', '결과', '두피', '순하다', '정력', '좋다'],
 ['제품', '좋다', '또', '구매', '의사'],
 ['개운하다', '깨끗하다', '느낌', '풍부하다', '거품', '머리', '덜', '빠지다'],
 ['샴푸', '뒤', '바로', '씻다', '엄청', '시원하다'],
 ['자다', '받다'],
 ['샴푸', '후', '시원'],
 ['머리', '시원하다'],
 ['개운하다', '용감', '좋다'],
 ['정력', '엄청', '좋다', '일단', '써다', '보다', '좋다', '같다'],
 ['번째', '사용', '이다', '좋다'],
 ['배송',
  '칼',
  '배송',
  '이다',
  '빨리',
  '오다',
  '깜짝',
  '놀라다',
  '정력',
  '총',
  '사용',
  '해보다',
  '뽀드득',
  '두피',
  '머리',
  '씻기다',
  '기분',
  '이다',
  '향기',
  '강하다',
  '않다',
  '잔향',
  '없다',
  '깔끔하다',
  '냄새',
  '가나',
  '제품',
  '이다',
  '탈모',
  '기능',
  '사용',
  '확인',
  '어렵다',
  '달',
  '정도',
  '사용',
  '후',
  '효과',
  '보다',
  '것',
  '같다',
  '아직',
  '은',
  '기존',
  '샴푸',
  '비슷하다',
  '빠지다',
  '쿨링감',
  '두피',
  '시원하다',
  '해주다',
  '하나',
  '찬물',
  '씻다',
  '않다',
  '그렇다',
  '쿨하다',
  '느낌',
  '없다',
  '효과',
  '보기',
  '위해',
  '두피',
  '마사지',
  '시간',
  '좀',
  '두다',
  '행궈',
  '것',
  '같다',
  '탄산',
  '샴푸',
  '사용',
  '처음',
  '탈모',
  '예방',
  '효과',
  '기대하다',
  '더',
  '사용',
  '해보다'],
 ['딥',
  '클린',
  '탄산',
  '쿨링',
  '샴푸',
  '제품',
  '명',
  '진짜',
  '머리',
  '감',
  '때',
  '시원하다',
  '청량감',
  '여태',
  '써다',
  '보다',
  '제품',
  '완전하다',
  '다르다',
  '좋다',
  '두피',
  '열',
  '내려가다',
  '확실하다',
  '체감',
  '되다',
  '평소',
  '하루',
  '안',
  '감다',
  '생기다',
  '각질',
  '어깨',
  '위',
  '비듬',
  '조금씩',
  '내려앉다',
  '지금',
  '그렇다',
  '전혀',
  '없다',
  '모발',
  '힘',
  '약하다',
  '볼륨',
  '감',
  '부족하다',
  '지금',
  '모발',
  '힘',
  '조금',
  '살아나다',
  '느낌',
  '이다',
  '블랙',
  '포레',
  '이',
  '샴푸',
  '강력',
  '추천'],
 ['엄청', '시원하다', '또', '구매', '만족하다'],
 ['두피',
  '골고루',
  '바르다',
  '시간',
  '좀',
  '지나다',
  '씻다',
  '시원하다',
  '그',
  '효과',
  '오래',
  '가지다',
  '않다',
  '그래도',
  '거품',
  '자다',
  '나오다',
  '냄새',
  '좋다',
  '일단',
  '달',
  '써다',
  '보다',
  '알',
  '것',
  '같다',
  '자다',
  '쓰다'],
 ['시원하다', '탄산', '감', '일품', '샴푸'],
 ['뽀득',
  '거릴',
  '정도',
  '괜춘',
  '피부',
  '보다',
  '피부',
  '기름',
  '흐르다',
  '확실하다',
  '정력',
  '좋다',
  '아직',
  '달이',
  '안되다',
  '탈모',
  '완화',
  '모르다',
  '시원하다',
  '피케',
  '어',
  '확실하다',
  '좋다'],
 ['덥다', '여름', '시원하다', '쓰기', '좋다'],
 ['오래',
  '쓰다',
  '않다',
  '아직',
  '은',
  '자다',
  '모르다',
  '머리',
  '감고',
  '나다',
  '두피',
  '시원하다',
  '느낌',
  '꾸준하다',
  '써다',
  '보다'],
 ['배송', '빠르다', '오늘', '첨', '써다', '보다', '시원하다', '좋다'],
 ['아주', '만족하다', '나중', '또', '필요하다', '재다'],
 ['썩', '좋다', '아직', '못', '느끼다'],
 ['머리', '더', '빠지다', '여'],
 ['머리', '더', '빠지다', '여'],
 ['자다', '사용'],
 ['시원하다', '좋다', '요'],
 ['파스', '같다', '향', '나다', '확실하다', '비듬', '머리카락', '빠지다', '줄다'],
 ['오다',
  '사은',
  '품',
  '대박',
  '제품',
  '쓰기',
  '전',
  '기분',
  '좋다',
  '사이즈',
  '보고',
  '품',
  '잘',
  '못',
  '오다',
  '자다',
  '쓰다'],
 ['거품', '잘나다', '정력', '좋다'],
 ['오래', '쓰다', '두피', '좀', '자극', '참고'],
 ['처음', '구입', '해봤다', '자다', '써다', '보다'],
 ['일단', '두피', '굉장하다', '시원하다', '점', '정말', '좋다'],
 ['신속하다', '뉴', '매달', '감사하다'],
 ['정력',
  '만족하다',
  '딥',
  '클린',
  '샴푸',
  '달리',
  '모발',
  '탈락',
  '늘어나다',
  '탈모',
  '케어',
  '좀',
  '아쉬움'],
 ['너무', '시원하다', '자극', '적', '않다', '좋다'],
 ['여름', '시원하다', '쓸다', '수'],
 ['여름철', '두피', '열', '심다', '블랙', '포레', '샴푸', '사용', '두피', '시원하다'],
 ['머리카락',
  '심각하다',
  '많이',
  '빠지다',
  '비듬',
  '지금',
  '두피',
  '반짝반짝',
  '빛나다',
  '머리카락',
  '거의',
  '안',
  '빠지다'],
 ['샴푸', '정력', '좋다', '것', '같다', '쿨링', '효과'],
 ['하하', '아빠', '주다'],
 ['사실', '크다', '효과', '모르다', '나쁘다', '않다'],
 ['우어', '어어', '어', '루웅'],
 ['빠르다', '배송', '좋다', '향', '좋다'],
 ['거품',
  '쫀뽄',
  '두피',
  '시원하다',
  '좋다',
  '헹굴땐',
  '모발',
  '약간',
  '뻣뻣하다',
  '같다',
  '말리',
  '나다',
  '부드럽다',
  '아직',
  '사용',
  '한지',
  '며칠',
  '안',
  '돼다',
  '탈모',
  '효과',
  '모르다',
  '꾸준하다',
  '사용',
  '해보다'],
 ['거품', '쫀쫀', '거품', '이풍', '성', '햐용'],
 ['머리', '뻣뻣하다', '트리', '트', '멀다', '틀다', '필수', '냄새', '상쾌하다', '시원하다', '정력', '좋다'],
 ['처음',
  '사용',
  '땐',
  '두피',
  '엄청',
  '시원하다',
  '금은',
  '너',
  '무덥다',
  '그렇다',
  '저',
  '이다',
  '탈모',
  '계속',
  '진행중',
  '많이',
  '빠지다'],
 ['감사하다', '한번', '써다', '보다', '아직', '은', '잘', '모르다', '쿨샴푼데', '시원하다', '않다'],
 ['좋다', '대신', '찌다', '지성', '분', '들', '번', '감다', '덜', '떡', '것', '같다'],
 ['처음', '써다', '효과', '모르다', '생각'],
 ['자다', '쓰다', '조금', '탈모', '덜', '진행', '되어다', '좋다'],
 ['사용', '나다', '시원하다', '좋다'],
 ['어제',
  '배송',
  '받다',
  '밤',
  '써다',
  '보다',
  '이렇게',
  '쏘다',
  '샴프',
  '처음',
  '요',
  '시원하다',
  '쿨',
  '샴프중',
  '단연',
  '가지',
  '중',
  '일단',
  '개',
  '구입',
  '것',
  '구입',
  '다음',
  '샴프',
  '이',
  '제품',
  '사용'],
 ['좋다', '신랑', '탈모', '효과'],
 ['시원하다', '좋다', '거', '같다', '신랑', '탈모', '약간', '효과', '좋다', '좋다'],
 ['여름', '쓰기', '굉장하다', '좋다', '샴푸', '이다', '정력', '정말', '좋다', '재다'],
 ['정은', '좋다', '거', '같다', '제', '두피', '안', '맞다', '같다'],
 ['머리', '감', '때', '시원하다', '좋다'],
 ['만족하다', '재다'],
 ['순하다',
  '거품',
  '자다',
  '나',
  '아빠',
  '동생',
  '머리',
  '쉬다',
  '유',
  '분',
  '많이',
  '생기다',
  '불편하다',
  '아빠',
  '하루',
  '번',
  '샴푸',
  '동생',
  '하루',
  '번',
  '샴푸',
  '엄마',
  '나',
  '하루',
  '번',
  '샴푸',
  '일반',
  '샴푸',
  '사용',
  '저희',
  '가족',
  '다',
  '번만',
  '샴푸',
  '씻다',
  '나',
  '머리',
  '살짝',
  '무겁다',
  '느끼다',
  '탈모',
  '효과',
  '달',
  '사용',
  '해보다',
  '자다',
  '모르다',
  '재다',
  '안',
  '기름',
  '많이',
  '지다',
  '사다'],
 ['너무',
  '마음',
  '들다',
  '향',
  '약간',
  '니베아',
  '쉐',
  '이빙',
  '젤',
  '향',
  '비슷하다',
  '스킨',
  '향',
  '절대',
  '아니다',
  '매력',
  '적',
  '남자',
  '향',
  '나다',
  '감다',
  '시원하다',
  '거품',
  '잘나다',
  '자다',
  '씻다',
  '너무',
  '좋다',
  '재',
  '주문'],
 ['자극', '시원하다', '느낌', '가격', '대비', '만족하다'],
 ['써다', '보고', '또', '항', '여'],
 ['머리', '엄청', '뻗다', '뻗다', '해저'],
 ['시원하다', '근데', '엄청', '뻣뻣하다'],
 ['시원하다', '근데', '엄청', '뻣뻣하다'],
 ['꾸준하다', '사용', '확실하다', '쿨링감'],
 ['시원하다',
  '정력',
  '좋다',
  '것',
  '같다',
  '몇',
  '일',
  '써다',
  '두피',
  '조금',
  '간지럽다',
  '조금',
  '아쉽다',
  '제',
  '두피',
  '자다',
  '안',
  '맞다',
  '건지다',
  '조금',
  '더',
  '써다',
  '보다'],
 ['배송', '엄청', '빠르다', '좋다'],
 ['만족하다', '재다', '매해', '두피', '깨끗하다', '느낌'],
 ['두번째',
  '구매',
  '이다',
  '머리카락',
  '가늘다',
  '두피',
  '약하다',
  '샴푸',
  '많이',
  '신경',
  '쓰다',
  '편입',
  '니',
  '일단',
  '감다',
  '시원하다',
  '느낌',
  '거품',
  '잘',
  '일어나다',
  '두피',
  '시원하다',
  '간지럽다',
  '움',
  '덜하다',
  '만족하다',
  '사용'],
 ['아직', '사용', '전이', '예쁘다', '쓰다'],
 ['빠르다', '배송', '행사', '용량', '샴푸', '개', '아주', '만족하다'],
 ['달',
  '사용',
  '후기',
  '쿨링감',
  '청량감',
  '샴푸',
  '비다',
  '월등하다',
  '특히',
  '미지근하다',
  '물',
  '때',
  '찬물',
  '때',
  '찬물',
  '이',
  '샴푸',
  '사용',
  '엄청',
  '시원하다',
  '탈모증',
  '상',
  '완화',
  '때문',
  '구매',
  '머리카락',
  '탈락',
  '수',
  '크게',
  '좋아지다',
  '않다',
  '두피',
  '샴프',
  '쿨링감',
  '좋다',
  '쓰다',
  '싶다',
  '분',
  '좋다'],
 ['확실하다',
  '쿨링감',
  '좋다',
  '금방',
  '진정',
  '되다',
  '해',
  '초록색',
  '써다',
  '보다',
  '저',
  '파란색',
  '피부',
  '더',
  '맞다'],
 ['머리카락', '많이', '빠지다', '딸', '위해', '저번', '구매', '효과', '눈', '띄다', '보', '재', '주문'],
 ['아직', '효과', '자다', '모르다', '꾸준하다', '사용', '해보다'],
 ['두피', '손상', '많이', '되어다', '자극', '심하다', '않다', '너무', '좋다'],
 ['좋다', '습', '니', '다'],
 ['쿨링', '오래', '지속', '되다', '않다', '약간', '샴푸', '새'],
 ['시원하다', '깔끔하다', '씻기다', '덥다', '꾸다', '꾸다', '요즘', '좋다'],
 ['두피', '청', '감', '좋다', '탈모', '좋다'],
 ['피케', '어', '탈모', '좋다', '감다', '청량감', '굿', '이다'],
 ['두번째',
  '구매',
  '이다',
  '사용',
  '시',
  '시원하다',
  '깨끗해지다',
  '느낌',
  '너무',
  '좋다',
  '계속',
  '사용',
  '같다'],
 ['처음',
  '사용',
  '때',
  '쿨링감',
  '자다',
  '모르다',
  '샴푸',
  '두다',
  '다음',
  '물',
  '헹구',
  '진짜',
  '개운하다',
  '깔끔하다',
  '쿨링감',
  '느껴지다',
  '두피',
  '가다',
  '많이',
  '사라지다',
  '만족하다',
  '단점',
  '사용',
  '후',
  '입구',
  '거품',
  '몽글몽글',
  '조금씩',
  '떨어지다',
  '병',
  '흐르다'],
 ['거품', '적당하다', '시원하다', '감다', '탈모', '방지', '더', '사용', '해보다', '같다'],
 ['시원하다', '자다', '쓰다'],
 ['생각', '시원하다', '느낌', '없다', '가려움', '좀', '덜하다', '사은', '품다', '주시', '너무', '좋다'],
 ['블랙',
  '포레',
  '제품',
  '쓰다',
  '두피',
  '트러블',
  '거의',
  '다',
  '나다',
  '예전',
  '두피',
  '울긋불긋하다',
  '이제',
  '자세하다',
  '들여다보다',
  '티',
  '안',
  '날다',
  '정도',
  '깨끗해지다'],
 ['시원하다', '좋다', '잘쓰다'],
 ['거품', '잘나다', '두피', '시원하다'],
 ['제품', '품질', '정력', '만족하다'],
 ['자극', '없다', '상쾌하다', '만족하다'],
 ['두피', '냄새', '제거', '우수하다', '정력', '좋다'],
 ['쿨링감', '좋다', '자극', '적', '않다', '두피', '건강하다', '느끼다', '가족', '함께', '쓰다'],
 ['적다',
  '양으로',
  '거품',
  '많이',
  '나다',
  '약간',
  '화하다',
  '느낌',
  '후',
  '두피',
  '시원하다',
  '자다',
  '감다',
  '느낌',
  '드네',
  '단',
  '많이',
  '뻗다',
  '뻗다',
  '지기',
  '트리트먼트',
  '필요하다'],
 ['시원시원하다', '머리', '시원하다', '기분', '너무나', '좋다'],
 ['달',
  '후기',
  '이다',
  '리뷰',
  '보',
  '바이럴',
  '마케팅',
  '리뷰',
  '들',
  '많다',
  '실',
  '사용자',
  '이다',
  '사실',
  '분들',
  '참고',
  '바라다',
  '좋다',
  '샴푸',
  '생각',
  '일단',
  '달',
  '사용',
  '해보다',
  '결과',
  '재다',
  '의사',
  '없다',
  '일단',
  '통',
  '다',
  '쓸다',
  '다',
  '쓰다',
  '나서다',
  '어떻다',
  '모르다',
  '일단',
  '달이',
  '지난',
  '현재',
  '재다',
  '의사',
  '없다',
  '효과',
  '샴푸',
  '후',
  '머리',
  '풍',
  '성해',
  '보이다',
  '효과',
  '크다',
  '않다',
  '지성',
  '두피',
  '탈모',
  '보통',
  '하루',
  '머리',
  '두',
  '번',
  '감다',
  '아침',
  '외출',
  '전',
  '머리',
  '감다',
  '걸',
  '이',
  '샴푸',
  '하진',
  '않다',
  '것',
  '추천',
  '드리다',
  '효과',
  '거의',
  '제로',
  '머리카락',
  '축',
  '내려오다',
  '볼륨',
  '감',
  '제로',
  '되다',
  '가뜩이나',
  '숱',
  '없다',
  '이',
  '샴푸',
  '더',
  '그렇다',
  '보이다',
  '쓸다',
  '밤',
  '샤워',
  '때',
  '쓸다',
  '정력',
  '거품',
  '엄청나다',
  '자다',
  '나다',
  '정력',
  '하나',
  '정말',
  '끝내주다',
  '두피',
  '열',
  '도나',
  '내다',
  '주다',
  '도',
  '얼마나',
  '크다',
  '온도',
  '차',
  '이',
  '광고',
  '담당자',
  '자다',
  '모르다',
  '듯',
  '아빠',
  '스킨',
  '냄새',
  '나서다',
  '약간',
  '멘솔',
  '향',
  '나다',
  '바람',
  '불면',
  '시원하다',
  '느낌',
  '두피',
  '열',
  '도',
  '씩',
  '내려가다',
  '것',
  '전혀',
  '모르다',
  '광고',
  '카메라',
  '두피',
  '열',
  '확',
  '내려가다',
  '모습',
  '보이다',
  '아마',
  '찬',
  '물',
  '감고',
  '얼마',
  '지나다',
  '않다',
  '상태',
  '촬영',
  '것',
  '아니다',
  '싶다',
  '이',
  '리뷰',
  '보다',
  '샴푸',
  '얼마나',
  '사용',
  '머리',
  '감다',
  '뒤',
  '몇',
  '시간',
  '뒤',
  '촬영',
  '물',
  '꼼꼼하다',
  '시간대',
  '기재',
  '해주다',
  '가려움증',
  '그렇다',
  '거일',
  '수도',
  '참고',
  '그렇게',
  '순하다',
  '성분',
  '샴푸',
  '아니다',
  '것',
  '같다',
  '느낌',
  '듭니',
  '미녹시딜',
  '바르다',
  '두피',
  '빨갛다',
  '가다',
  '워',
  '로게인펌',
  '갈아타다',
  '이',
  '샴푸',
  '사용',
  '도중',
  '그',
  '때',
  '가려움증',
  '비슷하다',
  '느낌',
  '들다',
  '잠시',
  '원래',
  '쓰다',
  '다슈',
  '샴푸',
  '돌아오다',
  '화학',
  '적',
  '성분',
  '들',
  '무지하다',
  '일반',
  '구매',
  '자의',
  '입장',
  '보기',
  '샴푸',
  '아빠',
  '스킨',
  '냄새',
  '꽤',
  '나다',
  '거품',
  '엄청나다',
  '그렇게',
  '순하다',
  '성분',
  '이루어지다',
  '느낌',
  '들다',
  '않다',
  '아마',
  '그래서',
  '두피',
  '민감하다',
  '반응',
  '게',
  '아니다',
  '싶다',
  '산',
  '아깝다',
  '기존',
  '다슈',
  '다시',
  '블랙',
  '포레',
  '돌아오다',
  '또',
  '다시',
  '머리',
  '가다',
  '지면',
  '이',
  '샴푸',
  '저',
  '안',
  '맞다',
  '것',
  '이겠다',
  '결론',
  '정력',
  '및',
  '거품',
  '정말',
  '진짜',
  '끝내주다',
  '지금',
  '어느',
  '탈모',
  '샴푸',
  '들',
  '비교',
  '안',
  '되다',
  '정도',
  '이다',
  '정력',
  '집중',
  '이',
  '샴푸',
  '산다',
  '추천',
  '이다',
  '쉬다',
  '빨갛다',
  '가다',
  '워',
  '민감하다',
  '두피',
  '진짜',
  '두피',
  '열',
  '내려가다',
  '바라다',
  '마음',
  '이',
  '샴푸',
  '혹은',
  '모든',
  '탈모',
  '샴푸',
  '들',
  '가다',
  '나르다',
  '득',
  '모하',
  '해주다',
  '대감',
  '이',
  '샴푸',
  '선택',
  '않다',
  '것',
  '좋다',
  '것',
  '같다'],
 ['두피', '정말', '좋아지다'],
 ['쿨링', '효과', '좋다', '만족스럽다'],
 ['두피', '자극', '없다', '감', '많이', '줄어들다', '같다', '탈모', '도움', '되다', '같다'],
 ['꾸준하다', '사용', '해보다', '일단', '이전', '쓰다', '확실하다', '기름', '짐', '덜하다', '같다'],
 ['포장', '꼼꼼하다', '배송', '빨', '좋다'],
 ['쿨', '성분', '정말', '좋다', '여름', '쓰기', '정말', '좋다'],
 ['자다', '사용', '중', '이다', '꾸준하다', '써다', '보다'],
 ['샴푸', '후', '시원하다', '좋다'],
 ['남편', '원하다', '사주다', '시원하다', '상쾌하다', '감사하다'],
 ['두피', '시원하다', '사용', '조금', '흘러나오다', '진짜', '부분', '개선', '되어다', '좋다'],
 ['배송', '빨', '좋다'],
 ['라이브',
  '방송',
  '보고',
  '구매',
  '두피',
  '쿨링',
  '효과',
  '너무',
  '시원하다',
  '좋다',
  '여름',
  '더',
  '자다',
  '쓰다'],
 ['안', '쓸다', '때', '게', '흠'],
 ['안거', '같다', '아영', '시원', '쓰다'],
 ['계속', '사용', '보다', '효과', '알다', '같다'],
 ['만족하다', '사용', '단지', '펌프', '사용', '후', '일부', '노즐', '남다', '되어다', '지저분하다'],
 ['두피', '너무', '시월', '좋다'],
 ['빠르다', '배송', '정력', '좋다', '머리카락', '힘', '살다', '느낌', '꾸준하다', '사용', '해보다'],
 ['아직', '은', '모르다', '청량감'],
 ['사용', '전후', '탈모', '개선', '돼다', '차이점', '미흡'],
 ['샴푸', '쓴다', '갓', '머리', '가다', '엄청', '심햇', '늘다', '거', '쓰다', '가다', '진정', '되어다'],
 ['잘', '받다', '감사하다'],
 ['감다', '두피', '시원하다', '개운하다'],
 ['일단', '써다', '보다', '알다', '계속', '새다', '나오다', '것'],
 ['탄산', '뽀글뽀글', '기화', '두피', '쿨링'],
 ['아직',
  '번',
  '정도',
  '사용',
  '않다',
  '두피',
  '관리',
  '모르다',
  '무난',
  '거품',
  '매우',
  '자다',
  '나서다',
  '감기',
  '좋다',
  '단지',
  '다른',
  '분',
  '들',
  '새다',
  '무엇',
  '인',
  '확실하다',
  '알다',
  '이',
  '점',
  '개선',
  '야하다'],
 ['출산',
  '후',
  '머리',
  '너무',
  '심하다',
  '빠지다',
  '반신반의',
  '구매',
  '해봤다',
  '감고',
  '나다',
  '두피',
  '시원하다',
  '머리',
  '뻣뻣하다',
  '감',
  '트리',
  '트',
  '멀다',
  '틀다',
  '항시',
  '같이',
  '크게',
  '불편하다',
  '못',
  '느끼다'],
 ['배송', '빠르다', '제품', '좋다'],
 ['빠르다', '배송', '감사하다'],
 ['아직', '효과', '자다', '모르다', '돼다', '근데', '두피', '쿨링', '되다', '느낌'],
 ['탈모', '예방', '도움', '되어다', '재다', '시원하다', '좋다'],
 ['여름',
  '뜨겁다',
  '태양',
  '때문',
  '쿨링',
  '샴푸',
  '구매',
  '여러',
  '샴푸',
  '쓰다',
  '효과',
  '바',
  '요',
  '달',
  '후',
  '다시',
  '후기',
  '남다'],
 ['쿨링', '생각', '만큼', '않다', '평이', '좋다', '믿다', '꾸준하다', '써다', '보다'],
 ['날', '덥다', '때', '딱이다', '머리', '감다', '시원하다'],
 ['쿨하다',
  '아직',
  '크게',
  '모르다',
  '정력',
  '뛰어나다',
  '듯',
  '거품',
  '진짜',
  '부드럽다',
  '많이',
  '나다',
  '초',
  '딸',
  '더',
  '만족',
  '학',
  '더',
  '구입',
  '구'],
 ['아주', '시원하다', '오다', '여름', '거만', '쓸다', '같다'],
 ['시원하다', '느낌', '아주', '좋다'],
 ['아직', '안', '써다', '보다'],
 ['머리', '기름', '제거', '자다', '되다', '거품', '자다', '나다', '무엇', '머리', '시원하다'],
 ['처음', '사용', '효과', '좋다', '제품', '이면', '사용', '후', '재다', '예정', '이다'],
 ['제품', '나쁘다', '않다', '자다', '쓰다'],
 ['가격', '비싸다', '부분', '빼다', '괜찮다', '거', '같다'],
 ['시원', '정력', '좋다', '향', '좋다'],
 ['좋다', '좋다', '좋다', '좋다', '좋다', '좋다', '좋다', '좋다'],
 ['거품', '나', '좋다'],
 ['너무', '편하다', '좋다'],
 ['생각', '보다', '기능', '성', '확', '다가오다', '않다'],
 ['두피',
  '열',
  '많다',
  '두피',
  '온도',
  '낮추다',
  '주다',
  '구매',
  '아직',
  '번안',
  '사용',
  '샴푸',
  '쓸다',
  '때',
  '시원하다',
  '좋다'],
 ['샴푸', '감다', '시원하다', '좋다', '머리털', '덜', '빠지다', '같다'],
 ['아빠', '지루', '두피', '염', '구매', '드럈', '어', '꾸준하다', '써다', '보시'],
 ['시원하다', '정력', '좋다'],
 ['가려움', '사라지다', '비듬', '없어지다', '다른', '사람', '들', '추천', '중', '이다'],
 ['배송', '빠르다', '좋다', '또', '주문', '최고', '이다'],
 ['아직',
  '한번',
  '써다',
  '보다',
  '자다',
  '모르다',
  '정력',
  '괜찮다',
  '시간',
  '지나다',
  '두피',
  '기르다',
  '덜하다',
  '좋다'],
 ['상쾌하다', '느낌', '좋다'],
 ['아들', '잘쓰다', '만족스럽다'],
 ['두피',
  '트러블',
  '많다',
  '블랙',

In [178]:
len(cont_tokens)

916

In [174]:
good_tokens = []
for t in good:
    good_tokens.append(make_tokens(t))
good_tokens

[['앞머리',
  '모발',
  '이식',
  '프로',
  '스카',
  '띄엄띄엄',
  '먹다',
  '정수리',
  '광탈',
  '시작',
  '곧바로',
  '미녹실딜',
  '다모',
  '다트',
  '진행',
  '요',
  '샴푸',
  '쿠팡',
  '행사',
  '때',
  '사악하다',
  '가격',
  '보고',
  '그냥',
  '속',
  '늘다',
  '사다',
  '오다',
  '놓다',
  '거',
  '엘땡',
  '건강',
  '닥터',
  '사기꾼',
  '태평',
  '레',
  '뤼어',
  '따위',
  '어',
  '탈모',
  '이름',
  '꺼내다',
  '안되다',
  '쓰레기',
  '확실하다',
  '두피',
  '열',
  '각질',
  '비듬',
  '개선',
  '과',
  '뚜렸함',
  '알다',
  '샴푸',
  '머리',
  '나다',
  '직접',
  '적',
  '상관없다',
  '두피',
  '열도',
  '사실',
  '기분',
  '탓',
  '밉다',
  '녹다',
  '딜로',
  '확장',
  '되다',
  '내',
  '두피',
  '모낭',
  '쾌적하다',
  '환경',
  '만들다',
  '보다',
  '되다',
  '발포',
  '기술',
  '요',
  '손등',
  '살짝',
  '문지르다',
  '보다',
  '무슨',
  '매직',
  '같다',
  '부글부글',
  '방울',
  '커지다',
  '신기하다',
  '여',
  '틀다',
  '비싸다',
  '딱',
  '번만',
  '짜다',
  '거품',
  '장난',
  '아니다',
  '부글부글',
  '그냥',
  '속',
  '늘다',
  '한번',
  '씩',
  '들다',
  '써다',
  '보삼',
  '나',
  '만족하다',
  '좀',
  '더',
  '할인',
  '해주다',
  '삼',
  '그',
  '스댕',
  '용기',
  '리',
  '필로',
  '만들다',
  '가격',
  '내다',
  '삼',
  '그렇다',
  '세번',
  '퍼핑'],
 ['여름',
  '쓰기',
  '좋다',
  '세척',
  '력',
  '괜찮다',
  '편',
  '같다',
  '사실',
  '탈모',
  '샴푸',
  '효과',
  '없다',
  '알다',
  '그래도',
  '매일',
  '쓰다',
  '샴푸',
  '보다',
  '조금',
  '도움',
  '되다',
  '쓰리다',
  '두피',
  '크다',
  '자극',
  '없다',
  '무엇',
  '쫀득쫀득',
  '거품',
  '많이',
  '생기다',
  '뭔가',
  '더',
  '깨끗하다',
  '씻기다',
  '같다',
  '느낌',
  '이듭',
  '니',
  '용기',
  '깔끔하다',
  '화장실',
  '오래',
  '놔두다',
  '곰팡이',
  '같다',
  '자다',
  '안',
  '생기다',
  '같다',
  '재질',
  '안심',
  '이다'],
 ['샴푸',
  '사용',
  '해보다',
  '너무',
  '좋다',
  '완전',
  '굿',
  '머리카락',
  '조금',
  '뻣뻣하다',
  '여자',
  '들',
  '트리트먼트',
  '필수',
  '이기다',
  '여름철',
  '쓰기',
  '딱이다',
  '저희',
  '신랑',
  '너무',
  '시원하다',
  '좋다'],
 ['전반',
  '적',
  '적당하다',
  '쓸다',
  '제품',
  '같다',
  '쪽',
  '계열',
  '제품',
  '사용',
  '전',
  '여러가지',
  '제품',
  '두다',
  '고민',
  '리뷰',
  '많다',
  '평이',
  '괜찮다',
  '써다',
  '보다',
  '샴푸',
  '기분',
  '팃',
  '인',
  '모르다',
  '시원하다',
  '느낌',
  '거품',
  '엄청',
  '풍',
  '성하다',
  '않다',
  '적당하다',
  '감',
  '정도',
  '되다',
  '세척',
  '력',
  '경우',
  '씻기다',
  '건',
  '괜찮다',
  '자다',
  '되다',
  '좀더',
  '길다',
  '써다',
  '보다',
  '알다',
  '현재',
  '선',
  '반',
  '정도',
  '만족도',
  '이다'],
 ['감고',
  '나다',
  '머리',
  '시원하다',
  '지다',
  '요즘',
  '같이',
  '덥다',
  '여름',
  '끝',
  '마무리',
  '감',
  '좋다',
  '샴푸',
  '쿨링',
  '향',
  '기분',
  '나쁘다',
  '향',
  '그렇다',
  '않다',
  '향',
  '기분',
  '좋다',
  '쿨링',
  '향',
  '나다',
  '양모',
  '효과',
  '정도',
  '같다',
  '두피',
  '딱하다',
  '문제',
  '생기지',
  '않다',
  '이렇다',
  '샴푸',
  '보통',
  '나다',
  '심하다',
  '땡기다',
  '수',
  '그렇다',
  '느낌',
  '비슷하다',
  '종류',
  '샴푸',
  '비다',
  '덜하다',
  '가격',
  '살짝',
  '아쉽다'],
 ['저',
  '매우',
  '만족하다',
  '앞',
  '계속',
  '써다',
  '보다',
  '되다',
  '것',
  '같다',
  '지성',
  '두피',
  '좋다',
  '것',
  '같다',
  '샴푸',
  '나서다',
  '느낌',
  '괜찮다',
  '샴푸',
  '사실',
  '기능',
  '적',
  '요인',
  '뭐',
  '가격',
  '괜찮다',
  '다',
  '생각',
  '저',
  '고민',
  '되다',
  '한번',
  '사다',
  '써다',
  '보시',
  '것',
  '나쁘다',
  '않다',
  '것',
  '같다',
  '한번',
  '다',
  '들다',
  '사용',
  '해보다',
  '바라다',
  '추가',
  '적',
  '크게',
  '자극',
  '없다',
  '민감하다',
  '신분',
  '들',
  '쓰다',
  '좋다'],
 ['샴푸',
  '시원하다',
  '피자',
  '극',
  '없다',
  '깔끔하다',
  '재다',
  '의사',
  '원형탈모',
  '고생',
  '중',
  '좋아지다',
  '좋다',
  '년',
  '동안',
  '천천히',
  '진행중',
  '이다',
  '올해',
  '급속도',
  '머리',
  '빠지다',
  '느낌',
  '이다',
  '쿨',
  '샴푸',
  '광고',
  '다른',
  '샴푸',
  '들',
  '여럿',
  '써다',
  '보다',
  '대부분',
  '제품',
  '들',
  '쿨링',
  '기능',
  '초점',
  '맞추다',
  '샴푸',
  '두피',
  '시원하다',
  '머릿결',
  '상하',
  '경우',
  '많다',
  '정',
  '때',
  '뻣뻣하다',
  '제대로',
  '거품',
  '씻다',
  '않다',
  '경우',
  '많다',
  '이',
  '제품',
  '탄산',
  '거품',
  '뭔가',
  '포',
  '계속',
  '생기다',
  '그렇다',
  '느낌',
  '기대하다',
  '그것',
  '아니다',
  '같다',
  '다만',
  '머릿결',
  '지키다',
  '선',
  '적당하다',
  '쿨링',
  '과',
  '않다',
  '상큼',
  '향',
  '돋보이다',
  '제품',
  '이다',
  '물건',
  '어제',
  '받다',
  '이제',
  '딱',
  '번',
  '사용',
  '해봤다',
  '느낌',
  '좋다',
  '달',
  '지나다',
  '통',
  '다',
  '사용',
  '무렵',
  '재다',
  '매하',
  '되다',
  '바라다'],
 ['시원하다', '좋다'],
 ['샴푸',
  '사용',
  '시원하다',
  '뭔가',
  '타닥타닥',
  '느끼다',
  '날',
  '줄',
  '았',
  '늘다',
  '시원하다',
  '정도',
  '자',
  '이상',
  '쓰기',
  '어렵다',
  '향',
  '남자',
  '들',
  '어울리다',
  '향',
  '이다',
  '정력',
  '나쁘다',
  '않다',
  '것',
  '같다',
  '아쉽다',
  '점',
  '기존',
  '슈퍼',
  '마트',
  '쓰다',
  '샴푸',
  '크게',
  '다르다',
  '않다',
  '것',
  '이다',
  '그래서',
  '샴푸',
  '그냥',
  '자신',
  '맞다',
  '걸',
  '사용',
  '좋다',
  '것',
  '같다'],
 ['좋다',
  '시원하다',
  '쿨링감',
  '할인',
  '판매',
  '샴푸',
  '바꾸다',
  '고민',
  '중',
  '다모',
  '검색',
  '내용',
  '읽다',
  '보다',
  '지루',
  '성',
  '피부',
  '좋다',
  '두피',
  '열',
  '내리다',
  '효과',
  '지금',
  '쓰다',
  '샴푸',
  '다',
  '쓰다',
  '구매',
  '예정',
  '이다',
  '행사',
  '중이',
  '가격',
  '괜찮다',
  '것',
  '같다'],
 ['저',
  '엠',
  '자',
  '탈모',
  '좀',
  '오다',
  '이마',
  '휑',
  '부터',
  '샴푸',
  '란',
  '샴푸',
  '다',
  '찾다',
  '쓰다',
  '일단',
  '쿨하다',
  '향',
  '기분',
  '시원하다',
  '해주다',
  '거품',
  '터지다',
  '요',
  '느낌',
  '게',
  '활',
  '성제',
  '들어가다',
  '샴푸',
  '들',
  '안',
  '좋아하다',
  '일단',
  '시원하다',
  '좋다',
  '깔끔하다',
  '지다',
  '느낌',
  '향',
  '좋다',
  '아주',
  '다이나믹',
  '효과',
  '없다',
  '플라시보',
  '게',
  '상쾌하다',
  '샴푸',
  '향',
  '깨끗하다',
  '두피',
  '쿨링',
  '감다',
  '지금',
  '써다',
  '보다',
  '샴푸',
  '들',
  '중',
  '가장',
  '좋다',
  '것',
  '같다'],
 ['앞머리',
  '모발',
  '이식',
  '프로',
  '스카',
  '띄엄띄엄',
  '먹다',
  '정수리',
  '광탈',
  '시작',
  '곧바로',
  '미녹실딜',
  '다모',
  '다트',
  '진행',
  '요',
  '샴푸',
  '쿠팡',
  '행사',
  '때',
  '사악하다',
  '가격',
  '보고',
  '그냥',
  '속',
  '늘다',
  '사다',
  '오다',
  '놓다',
  '거',
  '엘땡',
  '건강',
  '닥터',
  '사기꾼',
  '태평',
  '레',
  '뤼어',
  '따위',
  '어',
  '탈모',
  '이름',
  '꺼내다',
  '안되다',
  '쓰레기',
  '확실하다',
  '두피',
  '열',
  '각질',
  '비듬',
  '개선',
  '과',
  '뚜렸함',
  '알다',
  '샴푸',
  '머리',
  '나다',
  '직접',
  '적',
  '상관없다',
  '두피',
  '열도',
  '사실',
  '기분',
  '탓',
  '밉다',
  '녹다',
  '딜로',
  '확장',
  '되다',
  '내',
  '두피',
  '모낭',
  '쾌적하다',
  '환경',
  '만들다',
  '보다',
  '되다',
  '발포',
  '기술',
  '요',
  '손등',
  '살짝',
  '문지르다',
  '보다',
  '무슨',
  '매직',
  '같다',
  '부글부글',
  '방울',
  '커지다',
  '신기하다',
  '여',
  '틀다',
  '비싸다',
  '딱',
  '번만',
  '짜다',
  '거품',
  '장난',
  '아니다',
  '부글부글',
  '그냥',
  '속',
  '늘다',
  '한번',
  '씩',
  '들다',
  '써다',
  '보삼',
  '나',
  '만족하다',
  '좀',
  '더',
  '할인',
  '해주다',
  '삼',
  '그',
  '스댕',
  '용기',
  '리',
  '필로',
  '만들다',
  '가격',
  '내다',
  '삼',
  '그렇다',
  '세번',
  '퍼핑'],
 ['지금',
  '써다',
  '보다',
  '제품',
  '중',
  '제일',
  '좋다',
  '만족',
  '이다',
  '주차',
  '후기',
  '글',
  '남기다',
  '향',
  '거품',
  '량',
  '쿨링감',
  '클렌징',
  '다',
  '최고',
  '남기다',
  '비교',
  '사진',
  '탄산',
  '쿨링',
  '샴푸',
  '탈모',
  '약',
  '두피',
  '관리',
  '제품',
  '달',
  '간',
  '사용',
  '전',
  '후',
  '사진',
  '여러가지',
  '제품',
  '써다',
  '효과',
  '대화',
  '되다',
  '비교',
  '사진',
  '샴푸',
  '긍정',
  '적',
  '영향',
  '크다',
  '같다',
  '가족',
  '주변',
  '지인',
  '적극',
  '추천',
  '하고프다',
  '샴푸',
  '이다'],
 ['이보',
  '좋다',
  '샴푸',
  '본적',
  '없다',
  '보통',
  '달',
  '넘다',
  '두피',
  '적응',
  '돼다',
  '난리',
  '나다',
  '달',
  '다',
  '돼다',
  '괜찮다',
  '떡',
  '것',
  '없다',
  '볼륨',
  '감',
  '좋다',
  '모발',
  '탈락',
  '갯수',
  '자다',
  '유지',
  '뭐',
  '하나',
  '빠지다',
  '없다',
  '가격',
  '정도',
  '착하다',
  '생각',
  '이',
  '샴푸',
  '정착',
  '쓰다',
  '감사하다'],
 ['두피',
  '열',
  '많다',
  '확실하다',
  '쿨링감',
  '좋다',
  '모발',
  '얇다',
  '편이',
  '축축',
  '치다',
  '샴푸',
  '쓰다',
  '모발',
  '되게',
  '힘',
  '얻다',
  '기분',
  '이다',
  '욥',
  '머리',
  '빠지다',
  '현상',
  '두피',
  '가려움',
  '확실하다',
  '줄다',
  '적다',
  '양으로',
  '충분하다',
  '거품',
  '나다',
  '점도',
  '넘다',
  '만족스럽다'],
 ['친구',
  '좋다',
  '사보다',
  '시원하다',
  '좋다',
  '원래',
  '두피',
  '열',
  '많다',
  '땀',
  '잘나다',
  '덥다',
  '여름날',
  '하루',
  '번',
  '정도',
  '머리',
  '감',
  '정도',
  '이다',
  '그래도',
  '제품',
  '사용',
  '개선',
  '되다',
  '좋다',
  '개운하다',
  '가격',
  '적당하다',
  '추가',
  '구매',
  '의사',
  '습'],
 ['가장',
  '크다',
  '장점',
  '가지',
  '두피',
  '열',
  '내다',
  '줌',
  '양모',
  '효과',
  '머리',
  '결',
  '거치다',
  '만들다',
  '않다',
  '대부분',
  '거품',
  '손바닥',
  '삼',
  '푸르다',
  '덜다',
  '거품',
  '내다',
  '구조',
  '이',
  '제품',
  '젖다',
  '모발',
  '샴푸',
  '닿다',
  '미세하다',
  '거품',
  '나기',
  '시작',
  '정말',
  '편하다'],
 ['샴푸',
  '시',
  '밀도',
  '높다',
  '꼼꼼하다',
  '씻기다',
  '거품',
  '풍',
  '성하다',
  '사용',
  '해보다',
  '제일',
  '좋다',
  '점',
  '머리카락',
  '탈락',
  '곗',
  '수입',
  '니',
  '여러가지',
  '탈모',
  '샴푸',
  '사용',
  '해봤다',
  '제품',
  '좋다',
  '정도',
  '아니다',
  '압도',
  '적',
  '머리카락',
  '탈락',
  '숫자',
  '다르다',
  '향',
  '좋다',
  '샴푸',
  '후',
  '머리',
  '시원하다',
  '상쾌하다',
  '머리카락',
  '부드럽다',
  '암튼',
  '만족',
  '이다',
  '전',
  '앞',
  '것',
  '정착'],
 ['탈모',
  '유목민',
  '주',
  '쓰다',
  '남기다',
  '찌다',
  '후기',
  '이다',
  '거품',
  '력',
  '완전',
  '쫀쫀',
  '탱글탱글',
  '오밀조밀하다',
  '거품',
  '너무',
  '좋다',
  '탈모',
  '샴푸',
  '중',
  '용감',
  '제일',
  '좋다',
  '것',
  '같다',
  '시원하다',
  '자극',
  '적',
  '않다',
  '적다',
  '쿨링감',
  '더',
  '좋다',
  '두피',
  '열',
  '도',
  '낮추다',
  '주다',
  '부분',
  '마음',
  '듭니',
  '향',
  '시원하다',
  '상쾌하다',
  '무난',
  '향',
  '사실',
  '탈모',
  '샴푸',
  '향',
  '때문',
  '구매',
  '않다',
  '디자인',
  '알루미늄',
  '엄청',
  '무겁다',
  '고급스럽다',
  '계속',
  '재다',
  '매하',
  '사용',
  '계획',
  '이다'],
 ['체험',
  '단',
  '이벤트',
  '받다',
  '보다',
  '다',
  '사용',
  '재',
  '구매',
  '의사',
  '탈모',
  '샴푸',
  '종류',
  '많다',
  '일단',
  '두피',
  '피로',
  '감',
  '덜',
  '들어가다',
  '느낌',
  '들다',
  '아직',
  '주',
  '사용',
  '안해',
  '직접',
  '적',
  '효과',
  '말씀',
  '못',
  '드리다',
  '탈모',
  '샴푸',
  '필요하다',
  '분',
  '들',
  '이면',
  '리스트',
  '참고',
  '용',
  '기억',
  '두다',
  '추천',
  '드리다'],
 ['가격',
  '조금',
  '세다',
  '편이',
  '그래도',
  '이름',
  '모르다',
  '업체',
  '만들다',
  '것',
  '대기업',
  '만들다',
  '샴푸',
  '더',
  '안정',
  '적',
  '않다',
  '싶다',
  '광고',
  '보고',
  '구매',
  '일단',
  '두피',
  '시원하다',
  '감촉',
  '용감',
  '좋다',
  '사실',
  '샴푸',
  '증모',
  '되다',
  '건',
  '믿다',
  '않다',
  '헤어',
  '보충',
  '용',
  '사용',
  '머리',
  '개운하다',
  '가벼워지다',
  '느낌',
  '낫',
  '베드',
  '생각',
  '한번',
  '씩',
  '사용',
  '해보다',
  '추천',
  '드리다',
  '싶다'],
 ['지금',
  '써다',
  '샴푸',
  '중',
  '젤',
  '맘',
  '들다',
  '떡',
  '것',
  '없다',
  '가다',
  '덜하다',
  '모발',
  '풍',
  '성하다',
  '좋다',
  '가격',
  '정도',
  '착하다',
  '편이',
  '비싸다',
  '샴푸',
  '많이',
  '써다',
  '보다',
  '가성',
  '비',
  '최고',
  '듯해',
  '원래',
  '샴푸',
  '달',
  '정도',
  '쓰다',
  '두피',
  '적응하다',
  '바꾸다',
  '샴푸',
  '아직',
  '그것',
  '없다',
  '한번',
  '써다',
  '보다',
  '추천',
  '드리다'],
 ['젖다',
  '모발',
  '샴푸',
  '덜다',
  '묻히다',
  '미세하다',
  '거품',
  '나기',
  '시작',
  '함',
  '머리',
  '감기',
  '정말',
  '편하다',
  '샴푸',
  '시',
  '시원하다',
  '느낌',
  '탈모',
  '의',
  '경우',
  '두피',
  '열',
  '때문',
  '샴푸',
  '후',
  '두피',
  '열',
  '내다',
  '효과',
  '양모',
  '효과',
  '좋다'],
 ['거품',
  '많다',
  '진짜',
  '편하다',
  '쿨링',
  '대비',
  '눈가',
  '시큰하다',
  '일도',
  '적다',
  '쪽',
  '만족스럽다',
  '가격',
  '약간',
  '비싸다',
  '용기',
  '간',
  '충분하다',
  '양은',
  '괜찮다',
  '느끼다',
  '효과',
  '적절하다',
  '정도',
  '고요',
  '정력',
  '높다'],
 ['두피',
  '시원시원하다',
  '뾰루지',
  '사라지다',
  '너무',
  '좋다',
  '용량',
  '많다',
  '아주',
  '좋다',
  '담',
  '살수',
  '또',
  '사다',
  '탈모',
  '효과',
  '같다',
  '잘',
  '모르다',
  '두피',
  '열도',
  '내',
  '려',
  '가다',
  '좋다',
  '았습니',
  '좋다'],
 ['광고',
  '보고',
  '구매',
  '아직',
  '사용',
  '하',
  '않다',
  '두피',
  '열',
  '감소',
  '시키다',
  '기분',
  '들다',
  '조금',
  '걱정',
  '떨치다',
  '채',
  '잠',
  '들다',
  '수',
  '용량',
  '많이',
  '들다',
  '한번',
  '구매',
  '오래',
  '사용',
  '수',
  '써다',
  '보고',
  '효과',
  '정말',
  '좋다',
  '재',
  '구매',
  '의사',
  '충분하다'],
 ['두피',
  '열',
  '때문',
  '항상',
  '고민',
  '이다',
  '다모',
  '광고',
  '보고',
  '구매',
  '시원하다',
  '것',
  '시원하다',
  '거',
  '거품',
  '정말',
  '예술',
  '이다',
  '제',
  '좋다',
  '탈모',
  '샴푸',
  '다',
  '써다',
  '보다',
  '조금',
  '짜다',
  '미세하다',
  '거품',
  '계속',
  '나서다',
  '부드럽다',
  '상쾌하다',
  '샴푸',
  '수',
  '진짜',
  '강',
  '추하다'],
 ['가격',
  '조금',
  '세다',
  '편이',
  '그래도',
  '이름',
  '모르다',
  '업체',
  '만들다',
  '것',
  '대기업',
  '만들다',
  '샴푸',
  '더',
  '안정',
  '적',
  '않다',
  '싶다',
  '광고',
  '보고',
  '구매',
  '일단',
  '두피',
  '시원하다',
  '감촉',
  '용감',
  '좋다',
  '사실',
  '샴푸',
  '증모',
  '되다',
  '건',
  '믿다',
  '않다',
  '헤어',
  '보충',
  '용',
  '사용',
  '머리',
  '개운하다',
  '가벼워지다',
  '느낌',
  '낫',
  '베드',
  '생각'],
 ['샴푸',
  '때',
  '정력',
  '좋다',
  '편이',
  '무엇',
  '시원하다',
  '느낌',
  '들다',
  '너무',
  '좋다',
  '탈모',
  '완화',
  '대한',
  '효과',
  '개월',
  '째',
  '사용',
  '중',
  '못',
  '느끼다',
  '아무래도',
  '샴푸',
  '효과',
  '기대하다',
  '어렵다',
  '꽤',
  '시원하다',
  '계속',
  '구매',
  '사용',
  '생각',
  '이다'],
 ['우선',
  '시원하다',
  '느낌',
  '나쁘다',
  '않다',
  '정력',
  '가지',
  '독일',
  '판매',
  '위',
  '광고',
  '혹',
  '구매',
  '개월',
  '정도',
  '사용',
  '샴푸',
  '임',
  '드',
  '라미',
  '틱',
  '효과',
  '느껴지다',
  '않다',
  '그래도',
  '일반',
  '샴푸',
  '나은',
  '점',
  '사용',
  '중',
  '감',
  '모발',
  '전체',
  '볼륨',
  '감',
  '정도',
  '만족감',
  '제공',
  '다',
  '느끼다',
  '사용',
  '후',
  '청량',
  '가다',
  '두피',
  '열',
  '많다',
  '신분',
  '들',
  '추천'],
 ['해외',
  '유학',
  '중',
  '여기다',
  '탈모',
  '샴푸',
  '과',
  '비싸다',
  '한국',
  '안',
  '알려지다',
  '샴푸',
  '많다',
  '고민',
  '이다',
  '저',
  '접근성',
  '좋다',
  '샴푸',
  '이다',
  '한국',
  '다른',
  '탈모',
  '샴푸',
  '마사지',
  '후',
  '헹궜었는데',
  '이',
  '비듬',
  '제거',
  '효과',
  '더',
  '좋다'],
 ['일단',
  '샤워',
  '후',
  '카페인',
  '특유',
  '성분',
  '쿨링',
  '효과',
  '좋다',
  '두피',
  '싸하다',
  '느낌',
  '주어',
  '확실하다',
  '두피',
  '열',
  '자체',
  '내려가다',
  '느낌',
  '듭니',
  '두피',
  '각질',
  '도',
  '충분하다',
  '제거',
  '되다',
  '같다',
  '다만',
  '오래',
  '사용',
  '시',
  '위',
  '같다',
  '느낌',
  '덜',
  '듭니'],
 ['알페신',
  '샴푸',
  '일반',
  '샴푸',
  '별',
  '점',
  '모르다',
  '향',
  '시원하다',
  '즉시',
  '깨끗해지다',
  '기분',
  '듭니',
  '근데',
  '디자인',
  '투',
  '박하다',
  '효과',
  '무조건',
  '좋다',
  '사다',
  '음',
  '아니다',
  '다르다',
  '찾기',
  '전',
  '계속',
  '쓰다',
  '같다'],
 ['평범하다',
  '딱하다',
  '장점',
  '없다',
  '광고',
  '많다',
  '같이',
  '구매',
  '가능하다',
  '리',
  '퀴드',
  '그게',
  '두피',
  '감',
  '내다',
  '정도',
  '탈모',
  '도움',
  '되다',
  '통',
  '사용',
  '효과',
  '보지',
  '못',
  '가격',
  '대비',
  '양은',
  '무난',
  '냄새',
  '무난'],
 ['애초',
  '샴푸',
  '크다',
  '기대',
  '안',
  '쓰기',
  '그냥',
  '저',
  '쓰다',
  '정력',
  '나쁘다',
  '않다',
  '약간',
  '시원하다',
  '맛',
  '좋다',
  '용',
  '일',
  '자주',
  '편이',
  '일',
  '때',
  '노려보다',
  '나쁘다',
  '않다',
  '같다'],
 ['일단',
  '사용',
  '해보다',
  '결과',
  '머리',
  '감고',
  '나다',
  '시원하다',
  '느낌',
  '들다',
  '여름',
  '사용',
  '좋다',
  '생각',
  '몇번',
  '사용',
  '해보다',
  '않다',
  '효과',
  '잘',
  '모르다',
  '이미',
  '많이',
  '사용',
  '되다',
  '제품',
  '보다',
  '믿다',
  '쓰기',
  '더',
  '사용',
  '해보다',
  '또',
  '글',
  '쓰다'],
 ['카페인',
  '성분',
  '들어가다',
  '샴푸',
  '탈모',
  '샴푸',
  '인기',
  '써다',
  '보다',
  '모발',
  '힘',
  '생기다',
  '같다',
  '나쁘다',
  '않다',
  '시원하다',
  '쿨링감',
  '좋다',
  '샴푸',
  '그렇다',
  '머리카락',
  '영향',
  '크게',
  '주다',
  '않다',
  '같다',
  '약',
  '먹다',
  '뭐'],
 ['일단',
  '향',
  '스포츠',
  '스타일',
  '시원하다',
  '향',
  '씻다',
  '때',
  '상쾌하다',
  '느낌',
  '좋다',
  '향',
  '사람',
  '호불호',
  '갈릴',
  '수',
  '거',
  '같다',
  '머리',
  '감고',
  '나다',
  '머리',
  '힘',
  '조금',
  '생기다',
  '느낌',
  '들다',
  '빗질',
  '해주다',
  '머리',
  '평소',
  '더',
  '부드럽다',
  '가라',
  '앉다',
  '느낌',
  '들다'],
 ['제',
  '쓰다',
  '제품',
  '이다',
  '향',
  '무난',
  '가격',
  '요새',
  '너무',
  '착하다',
  '지다',
  '다른',
  '샴푸',
  '많이',
  '써다',
  '보다',
  '것',
  '쓰다',
  '다시',
  '돌아오다',
  '아마',
  '트',
  '레이더스',
  '사시',
  '더',
  '싸다',
  '실수',
  '처음',
  '독일',
  '마켓',
  '어',
  '매'],
 ['샴푸',
  '때',
  '거품',
  '충분하다',
  '나다',
  '두피',
  '시원하다',
  '것',
  '확실하다',
  '느껴지다',
  '샴푸',
  '탈모',
  '완화',
  '되다',
  '득',
  '모하',
  '겠다',
  '크다',
  '기대',
  '갖다',
  '사용',
  '것',
  '아니다',
  '그렇다',
  '기분',
  '좋다',
  '깨끗하다',
  '시원하다',
  '만족스럽다',
  '용감',
  '가다',
  '주다',
  '비록',
  '기다리다',
  '데',
  '귀찮다',
  '음',
  '가져오다',
  '상품',
  '나쁘다',
  '점',
  '기억',
  '돼다',
  '처음',
  '구매',
  '때',
  '샴푸',
  '모발',
  '뿌리',
  '스며들다',
  '시간',
  '기다리다',
  '점',
  '모근',
  '확실하다',
  '영양분',
  '줄',
  '것',
  '같다',
  '믿음',
  '주다',
  '이',
  '샴푸',
  '머리',
  '감다',
  '하수',
  '구',
  '머리',
  '좀',
  '덜',
  '빠지다',
  '것',
  '같다'],
 ['멘톨',
  '많이',
  '들어가다',
  '시원하다',
  '화하다',
  '느낌',
  '두피',
  '열',
  '오르다',
  '저',
  '좋다',
  '확실하다',
  '감',
  '때',
  '빠지다',
  '양은',
  '줄어들다',
  '것',
  '같다',
  '남자',
  '스킨',
  '향수',
  '같다',
  '냄새',
  '강하다',
  '호불호',
  '갈리다',
  '저',
  '정수리',
  '냄새',
  '안나',
  '호',
  '이다'],
 ['일단',
  '샴푸',
  '후',
  '머리',
  '시원하다',
  '느껴지다',
  '정도',
  '정력',
  '막강',
  '년',
  '전',
  '독일',
  '가다',
  '때',
  '알',
  '되어다',
  '현지',
  '상당하다',
  '인기',
  '처음',
  '구입',
  '되어다',
  '만족감',
  '높다',
  '편입',
  '니',
  '저',
  '이전',
  '를',
  '사용',
  '개인',
  '적',
  '알페신',
  '샴푸',
  '후',
  '느낌',
  '더',
  '좋다',
  '것',
  '같다'],
 ['탈모',
  '샴푸',
  '찾다',
  '알페신',
  '좋다',
  '구매',
  '샴푸',
  '같다',
  '경우',
  '개인',
  '적',
  '정감',
  '별로',
  '이다',
  '거',
  '시원시원하다',
  '정이',
  '되다',
  '느낌',
  '것',
  '같다',
  '좋다',
  '점',
  '딱하다',
  '모르다',
  '많이',
  '사다',
  '사다',
  '같다'],
 ['확실하다',
  '피',
  '나스',
  '테',
  '리드',
  '약과',
  '함께',
  '사용',
  '시',
  '모량',
  '풍',
  '성하다',
  '느낌',
  '들다',
  '가격',
  '대',
  '무시',
  '못',
  '뿌리',
  '쪽',
  '두껍다',
  '자',
  '쪽',
  '많이',
  '채우다',
  '볼륨',
  '감',
  '살아나다',
  '향기롭다',
  '못',
  '요',
  '한번',
  '많이',
  '사용',
  '필요',
  '없다',
  '듯'],
 ['남성',
  '화장품',
  '향',
  '나다',
  '분사',
  '구가',
  '펌프',
  '식이',
  '아니다',
  '좀',
  '불편하다',
  '정력',
  '좋다',
  '탈모',
  '효과',
  '며칠',
  '안되다',
  '자다',
  '모르다',
  '모발',
  '힘',
  '좀',
  '들어가다',
  '느낌',
  '드네',
  '물론',
  '개인',
  '적',
  '느낌',
  '이다',
  '달',
  '써다',
  '보고',
  '재다',
  '예정',
  '이다'],
 ['독일',
  '제품',
  '믿다',
  '구매',
  '가격',
  '비싸다',
  '비싸다',
  '머리',
  '감고',
  '난후',
  '상쾌하다',
  '샴푸',
  '비교',
  '안되다',
  '정도',
  '좋다',
  '확실하다',
  '빠지다',
  '량',
  '좀',
  '줄',
  '거',
  '같다',
  '현재',
  '개월',
  '정도',
  '사용',
  '만족',
  '중',
  '이다'],
 ['카페인',
  '좋다',
  '년전',
  '계속',
  '쓰다',
  '세',
  '직구도',
  '말다',
  '풀다',
  '구매',
  '쉽다',
  '갓',
  '같다',
  '계속',
  '쓰다',
  '보다',
  '다른',
  '제품',
  '른',
  '무섭다',
  '못',
  '쓰다',
  '느낌',
  '상',
  '많이',
  '빠지다',
  '횟수',
  '줄어들다',
  '것',
  '같다',
  '시원하다'],
 ['독일',
  '제일',
  '유명하다',
  '샴푸',
  '통',
  '디자인',
  '맘',
  '들어서다',
  '사용',
  '해봤다',
  '용량',
  '사서',
  '가격',
  '적',
  '부분',
  '크게',
  '걱정',
  '안',
  '되다',
  '다른',
  '탈모',
  '샴푸',
  '비다',
  '머리',
  '힘',
  '세다',
  '느낌',
  '받다',
  '것',
  '검은색',
  '통',
  '그게',
  '향',
  '더',
  '좋다'],
 ['통째',
  '쓰다',
  '냄새',
  '맘',
  '들다',
  '샴푸',
  '나다',
  '머리카락',
  '약간',
  '힘',
  '생기다',
  '워낙',
  '얘기',
  '많이',
  '들다',
  '샴푸',
  '기대다',
  '열심히',
  '쓰다',
  '머리',
  '기름기',
  '좀',
  '줄어들다',
  '느끼다',
  '꾸준하다',
  '한번',
  '써다',
  '볼',
  '예정',
  '맥주',
  '효모',
  '쪽',
  '관심',
  '가다'],
 ['독일',
  '교환학생',
  '가다',
  '그때',
  '사용',
  '지금',
  '쿠팡',
  '용량',
  '사서',
  '쓰다',
  '머리',
  '지성',
  '지루',
  '성',
  '피부염',
  '같이',
  '저',
  '뽀득뽀득',
  '느낌',
  '좋다',
  '약',
  '복용',
  '같이',
  '자다',
  '쓰다'],
 ['정력',
  '좋다',
  '냄새',
  '상남자',
  '냄새',
  '저',
  '만족하다',
  '사용',
  '후',
  '머리카락',
  '힘',
  '생기다',
  '느낌',
  '모발',
  '양제',
  '흡수',
  '시키다',
  '느낌',
  '들다',
  '샴푸',
  '칠하다',
  '최소',
  '기다리다',
  '씻다',
  '야하다',
  '기다리다',
  '동안',
  '가려움',
  '덤',
  '이다'],
 ['세척',
  '잘',
  '되다',
  '것',
  '같다',
  '기분',
  '사용',
  '때',
  '광고',
  '많이',
  '안해',
  '저렴하다',
  '살',
  '수',
  '요즘',
  '유명하다',
  '탓',
  '가격',
  '예전',
  '오른',
  '것',
  '같다',
  '다만',
  '그래도',
  '개운하다',
  '가장',
  '좋다',
  '샴푸',
  '생각',
  '돼다'],
 ['감고',
  '나다',
  '시원하다',
  '모발',
  '튼튼하다',
  '느낌',
  '들다',
  '샴푸',
  '향',
  '시원시원하다',
  '감다',
  '개운하다',
  '가격',
  '엄청',
  '비싸다',
  '않다',
  '사용',
  '부담',
  '없다',
  '촉감',
  '좋다',
  '더',
  '좋다',
  '제품',
  '없다',
  '앞',
  '쭉',
  '사용',
  '거',
  '같다'],
 ['전체',
  '적',
  '시원하다',
  '용감',
  '좋다',
  '사용',
  '제품',
  '질',
  '질',
  '때',
  '괜찮다',
  '접근성',
  '좋다',
  '부담',
  '없이',
  '사용',
  '해보다',
  '좋다',
  '가격',
  '이다',
  '어디',
  '서나',
  '구매',
  '수',
  '제품',
  '고민',
  '신분',
  '한번',
  '접근',
  '해보다'],
 ['두피',
  '시원하다',
  '향',
  '좋다',
  '두피',
  '기름기',
  '말끔',
  '지우다',
  '대략',
  '간',
  '사용',
  '와이프',
  '항상',
  '향',
  '좋다',
  '자매',
  '품',
  '토너',
  '같이',
  '사용',
  '정수리',
  '냄새',
  '없다',
  '것',
  '같다',
  '가격',
  '이마트',
  '트',
  '레이더스',
  '코스트코',
  '저렴하다',
  '세트',
  '구매',
  '가능하다',
  '추천'],
 ['샴푸',
  '일정',
  '시간',
  '놔두다',
  '뒤',
  '물',
  '씻다',
  '두피',
  '시원하다',
  '상쾌하다',
  '멘솔',
  '같다',
  '느낌',
  '나다',
  '향',
  '취향',
  '타다',
  '제',
  '기준',
  '괜찮다',
  '두피',
  '일시',
  '적',
  '힘',
  '들어가다',
  '느낌',
  '받다'],
 ['디',
  '스',
  '자',
  '이징',
  '샴푸',
  '쓰다',
  '어쩔',
  '수',
  '없다',
  '열흘',
  '정도',
  '방향',
  '첨가',
  '되어다',
  '를',
  '일주일',
  '정도',
  '써다',
  '진짜',
  '머리',
  '말리다',
  '때',
  '평소',
  '많이',
  '빠지다',
  '거',
  '보고',
  '충격',
  '먹다',
  '이',
  '제품',
  '바로',
  '바꾸다',
  '일주일',
  '정도',
  '사용',
  '후',
  '빠지다',
  '머리',
  '거의',
  '없다',
  '정도',
  '확',
  '줄다',
  '샴푸',
  '후',
  '모발',
  '굵다',
  '느낌',
  '듭니'],
 ['머리',
  '빠지다',
  '않다',
  '도움',
  '주다',
  '빳빳',
  '느낌',
  '주다',
  '해주다',
  '좋다',
  '양도',
  '나름',
  '괜찮다',
  '제품',
  '특유',
  '시원하다',
  '느낌',
  '좋다',
  '두피',
  '마사지',
  '때',
  '자다',
  '문지르다',
  '시간',
  '두다',
  '뒤',
  '헹',
  '구어',
  '내면',
  '시원하다',
  '느낌',
  '꽤',
  '괜찮다',
  '숱',
  '유지',
  '도움',
  '줍다'],

In [175]:
len(good_tokens)

9874

In [176]:
bad_tokens = []
for t in bad:
    bad_tokens.append(make_tokens(t))
bad_tokens

[['스댕',
  '용기',
  '개',
  '이쁘다',
  '좋다',
  '원가',
  '너무',
  '비싸다',
  '내',
  '보기',
  '가격',
  '높다',
  '최대',
  '원인',
  '듯함',
  '요',
  '튜브',
  '만들다',
  '삼',
  '좀',
  '흐르다',
  '굳다',
  '요',
  '피',
  '같다',
  '돈',
  '아깝다',
  '움',
  '근데',
  '장점',
  '다',
  '커버',
  '함'],
 ['음',
  '꼭',
  '찾다',
  '적다',
  '가격',
  '탈모',
  '샴푸',
  '들',
  '다',
  '들다',
  '비싸다',
  '근데',
  '뭐',
  '다비',
  '싸다',
  '요'],
 ['스댕',
  '용기',
  '개',
  '이쁘다',
  '좋다',
  '원가',
  '너무',
  '비싸다',
  '내',
  '보기',
  '가격',
  '높다',
  '최대',
  '원인',
  '듯함',
  '요',
  '튜브',
  '만들다',
  '삼',
  '좀',
  '흐르다',
  '굳다',
  '요',
  '피',
  '같다',
  '돈',
  '아깝다',
  '움',
  '근데',
  '장점',
  '다',
  '커버',
  '함'],
 ['가격',
  '조금',
  '비싸다',
  '그래도',
  '새롭다',
  '기술',
  '적용',
  '되어다',
  '엄청나다',
  '쿨링감',
  '가지',
  '금액',
  '조금',
  '나가다',
  '수',
  '생각',
  '나쁘다',
  '점',
  '아니다',
  '사용',
  '상',
  '문제',
  '되다',
  '없다',
  '탄산',
  '쿨링',
  '샴푸',
  '사용',
  '때',
  '펌핑',
  '입구',
  '부분',
  '탄산',
  '거품',
  '남다',
  '인지',
  '사용',
  '되다',
  '듯'],
 ['특별하다', '없다'],
 ['딱하다', '없다'],
 ['샴푸', '용기', '무거', '움'],
 ['조금', '가격', '비싸다'],
 ['일상생활', '시', '향기', '많이', '아쉽다'],
 ['리', '퀴드', '같이', '사용', '효과', '조금', '귀찮다'],
 ['향',
  '호불호',
  '갈릴',
  '거',
  '같다',
  '액체',
  '색도',
  '일반',
  '적',
  '샴푸',
  '달라',
  '이',
  '부분',
  '취향',
  '따르다',
  '갈릴',
  '수',
  '것',
  '같다'],
 ['샴푸',
  '모발',
  '부리',
  '스며들다',
  '시간',
  '약',
  '걸리다',
  '때문',
  '두피',
  '도포',
  '후',
  '약',
  '기다리다',
  '씻다',
  '용법',
  '좀',
  '귀찮다',
  '머리',
  '매일',
  '감다',
  '매',
  '번',
  '사용',
  '때',
  '두피',
  '스며들다',
  '시간',
  '기다리다',
  '것',
  '성격',
  '급하다',
  '사람',
  '힘드다',
  '일로',
  '다가',
  '왓다'],
 ['우선', '가격', '비싸다', '용량', '적다', '딱하다', '모발', '굵다', '느낌', '없다'],
 ['그냥', '샴푸', '것', '같다'],
 ['샴푸', '짤때', '양', '조절', '약간', '힘드다', '부분'],
 ['용량', '사면', '좀', '가격', '저렴하다', '그래도', '비싸다', '같다'],
 ['머리', '뻣뻣하다', '어쩔', '수가', '없다', '같다'],
 ['탈모', '방지', '효과', '대해', '선', '획기', '적', '효과', '아직', '은', '못', '보다'],
 ['뽀득뽀득', '만큼', '건성', '이신', '분들', '조금', '안', '맞다', '같다'],
 ['가격', '좀', '비싸다', '편', '같다', '기다리다', '효과', '보다', '좀', '단점', '같다'],
 ['아쉽다', '건', '거품', '적다', '정도'],
 ['향', '호불호', '갈릴', '수', '용액', '색', '파래'],
 ['딱하다', '효과', '모르다'],
 ['가려움증',
  '해소',
  '비듬',
  '감소',
  '모발',
  '량',
  '증가',
  '등',
  '효과',
  '없다',
  '듯',
  '또한',
  '제품',
  '용기',
  '특성',
  '상',
  '용기',
  '짜다',
  '쓰다',
  '형태',
  '정량',
  '사용',
  '매우',
  '어렵다'],
 ['자',
  '이징',
  '샴푸',
  '서다',
  '때',
  '비슷하다',
  '샴포할',
  '때',
  '모발',
  '굉장하다',
  '뻣뻣하다',
  '사용',
  '초기',
  '두피',
  '살짝',
  '건조하다',
  '느낌',
  '들다',
  '었',
  '부분',
  '적',
  '각질',
  '좀',
  '생기다',
  '것',
  '같다',
  '지금',
  '괜찮다'],
 ['머리', '자라다', '효과', '없다', '보이다', '냄새', '호불호', '갈리다'],
 ['전만',
  '해외',
  '직구',
  '등',
  '통해',
  '저렴하다',
  '구매',
  '수',
  '국내',
  '정식',
  '수입',
  '이후',
  '판매',
  '가격',
  '급격하다',
  '상승',
  '함',
  '계속',
  '쓸다',
  '예정',
  '과거',
  '비다',
  '가격',
  '부담',
  '상당하다',
  '편'],
 ['솔직하다', '탈모', '도움', '되다', '모르다', '심리', '적', '만족감', '사용'],
 ['음',
  '제일',
  '중요하다',
  '점',
  '효과',
  '눈',
  '띄다',
  '나타나다',
  '않다',
  '것',
  '이다',
  '물론',
  '시원하다',
  '강렬하다',
  '느낌',
  '들다',
  '기다',
  '하나',
  '머리',
  '자라나다',
  '효과',
  '없다',
  '것',
  '같다'],
 ['쓸다', '머리', '너무', '뻣뻣하다', '모발', '힘', '생기다', '다르다'],
 ['예전',
  '좋다',
  '기억',
  '요즘',
  '탈모',
  '진짜',
  '너무',
  '심해지다',
  '다시',
  '사서',
  '사용',
  '탈모',
  '딱하다',
  '도움',
  '되다',
  '자다',
  '모르다',
  '아직',
  '사용',
  '한지',
  '얼마',
  '되다',
  '않다',
  '꾸준하다',
  '덜',
  '써다',
  '볼',
  '계획'],
 ['용기',
  '좀',
  '딱딱하다',
  '샴푸',
  '조절',
  '힘들다',
  '냄새',
  '나쁘다',
  '않다',
  '아주',
  '상남자',
  '냄새',
  '남',
  '아저씨',
  '스킨',
  '냄새',
  '나'],
 ['냄새', '별로', '샴푸', '짤때', '너무', '흐르다', '내리다'],
 ['생각',
  '건조하다',
  '느낌',
  '머리',
  '말리다',
  '직후',
  '수분',
  '감다',
  '찰랑거리다',
  '좋다',
  '생각',
  '매일',
  '쓰다',
  '보',
  '좀',
  '건조하다',
  '느낌',
  '들다'],
 ['확실하다',
  '제품',
  '탓',
  '인',
  '알',
  '수',
  '없다',
  '지루',
  '성',
  '피부염',
  '증상',
  '심하다',
  '때',
  '쓰다',
  '얼굴',
  '조금',
  '간지럽다',
  '감'],
 ['효과', '딱하다', '없다', '것', '같다'],
 ['가성',
  '비',
  '너무',
  '떨어지다',
  '형',
  '그냥',
  '물',
  '같다',
  '샴푸',
  '느낌',
  '많이',
  '들다',
  '않다',
  '또',
  '테',
  '너무',
  '독하다',
  '샴푸',
  '때',
  '눈',
  '많이',
  '아프다',
  '붉다',
  '부작용'],
 ['시중', '팔다', '모델', '너무', '작다', '비싸다', '감', '인터넷', '주문', '느낌', '상', '든든하다'],
 ['국내',
  '올리브영',
  '같다',
  '매장',
  '용량',
  '보통',
  '용량',
  '안',
  '나오다',
  '얄궂',
  '덥다',
  '그래서',
  '직구',
  '용량',
  '사서',
  '써다',
  '부분',
  '좀',
  '아쉽다'],
 ['정력', '좋다', '자다', '모르다', '좀', '린스', '같다', '재질'],
 ['일단',
  '양',
  '비다',
  '비싸다',
  '편',
  '속',
  '함',
  '일반',
  '적',
  '샴푸',
  '다르다',
  '거품',
  '자다',
  '안',
  '나다',
  '래서',
  '두피',
  '정력',
  '그냥',
  '보통',
  '것',
  '같다',
  '이중',
  '샴푸',
  '불편하다',
  '말리',
  '나서다',
  '두피',
  '약간',
  '감',
  '느끼다',
  '시간',
  '지나다',
  '부분',
  '적',
  '살짝',
  '간질간질',
  '거리',
  '현상',
  '발생',
  '크게',
  '염증',
  '생기다',
  '것',
  '없다',
  '욕',
  '일단',
  '더',
  '사용',
  '해보다',
  '일시',
  '적',
  '건지다',
  '안',
  '맞다',
  '건지다',
  '알',
  '수',
  '것',
  '같다'],
 ['정력', '강하다', '두피', '바짝', '말르다', '버리다', '안좋다', '것', '같다', '함'],
 ['저', '딱하다', '효능', '보지', '못'],
 ['샴푸', '용기', '편리', '않다'],
 ['제일', '중요하다', '효과', '없다'],
 ['엄창', '효능', '기대하다', '말다', '샴푸', '그냥', '샴푸', '이다'],
 ['효과', '없다'],
 ['순하다',
  '않다',
  '성분',
  '그렇다',
  '기억',
  '재다',
  '의사',
  '별',
  '개',
  '마무리',
  '주관',
  '적',
  '의견',
  '이다'],
 ['일단', '제품', '양', '너무', '적다', '너무', '금방', '다시', '사다', '느낌'],
 ['묽다', '느낌', '그', '부분', '약간', '아쉽다'],
 ['형', '상당하다', '묽다', '지루', '두피', '염', '본인', '머리', '많이', '빠지다'],
 ['가격', '사악하다', '내용물', '작다'],
 ['아직', '탈모', '효과', '모르다', '따다'],
 ['직구',
  '아니다',
  '용량',
  '대비',
  '가격',
  '좀',
  '확',
  '오다',
  '닿다',
  '효과',
  '이',
  '제품',
  '역시',
  '없다'],
 ['뻣뻣하다',
  '모발',
  '힘',
  '생기다',
  '착각',
  '수',
  '모근',
  '힘',
  '실리다',
  '것',
  '아니다',
  '정수리',
  '힘',
  '없다',
  '분',
  '들',
  '샴푸',
  '후',
  '정수리',
  '볼륨',
  '살아나다',
  '기적',
  '적',
  '효과',
  '기대하다',
  '어렵다',
  '뒤통수',
  '볼륨',
  '살아나다',
  '샴푸',
  '후',
  '소량',
  '컨디셔너',
  '모발',
  '부드럽다',
  '해주다',
  '오히려',
  '전체',
  '적',
  '밸런스',
  '맞추다',
  '적절하다',
  '힘',
  '찾다',
  '수',
  '느끼다'],
 ['기존', '쿨링', '샴푸', '차이', '못', '느끼다'],
 ['냄새', '저', '별로'],
 ['결국', '머리카락', '뻣뻣하다', '만들다', '굵다', '보이', '같다', '향', '좀'],
 ['개인',
  '적',
  '지속',
  '적',
  '효과',
  '보',
  '이기',
  '빠지다',
  '량',
  '그대로',
  '절',
  '잘',
  '안',
  '맞다',
  '외'],
 ['사실',
  '그냥',
  '샴푸',
  '이상',
  '그',
  '이하',
  '아니다',
  '효능',
  '가지다',
  '같다',
  '개월',
  '이상',
  '쓰다',
  '가격',
  '생각',
  '메리트',
  '없다',
  '같다'],
 ['탈모', '효과', '모르다'],
 ['탈모', '효과', '모르다'],
 ['사실', '효능', '전혀', '모르다', '샴푸', '자극', '편이'],
 ['형', '묽다', '편이', '용기', '주둥이', '부분', '많이', '묻다'],
 ['탈모', '개선', '효과', '자다', '모르다'],
 ['화해', '어플', '사', '보다', '안좋다', '성분', '좋다'],
 ['다',
  '좋다',
  '향',
  '너무',
  '강하다',
  '여자',
  '쓰기',
  '남성',
  '향수',
  '느낌',
  '많이',
  '나다',
  '뚜껑',
  '조금',
  '불편하다'],
 ['많이',
  '사용',
  '않다',
  '이상',
  '정력',
  '크게',
  '떨어지다',
  '같다',
  '간간히',
  '정후',
  '머리',
  '많이',
  '뽀드득',
  '거릴때',
  '머리',
  '수분',
  '다',
  '빠지다'],
 ['사용', '해보다', '탈모', '샴푸', '중', '샴푸', '후', '머리', '푸석거리다', '가장', '심하다'],
 ['탈모', '샴푸', '머리카락', '자라다', '않다'],
 ['탈모', '방지', '같다', '효과', '자다', '느끼다', '못'],
 ['사제품', '들', '부드럽다', '않다'],
 ['가격', '좀', '비싸다'],
 ['진짜', '효과', '아무', '모르다'],
 ['떡', '잘', '지다', '저', '자다', '안', '맞다', '재다', '매다', '안', '예정'],
 ['일단',
  '머리',
  '너무',
  '뻑뻑',
  '힘드다',
  '더',
  '뽑히다',
  '느낌',
  '효과',
  '그렇게',
  '뛰어나다',
  '생각',
  '되다',
  '않다'],
 ['부족하다', '과학', '적', '근거'],
 ['효과', '미지수'],
 ['이', '가격', '대', '더', '좋다', '선택', '많다', '같다'],
 ['그', '좋다', '점', '없다'],
 ['적어도', '나', '늘다', '안', '맞다', '같다', '재다', '의사'],
 ['탈모',
  '예방',
  '되다',
  '의문',
  '가격',
  '비싸다',
  '팍팍',
  '쓰다',
  '못',
  '아쉬움',
  '가끔',
  '코스트코',
  '저렴하다',
  '구입',
  '가능하다'],
 ['계속', '사용', '두피', '많이', '건조하다', '기분'],
 ['탈모', '딱하다'],
 ['위', '동일', '아쉽다', '잠', '계면'],
 ['딱하다', '탈모', '효과', '없다', '것', '같다'],
 ['탈모', '좋아지다', '효과', '자다', '못', '느끼다'],
 ['헤드엠숄더',
  '성분',
  '더',
  '많이',
  '안좋다',
  '듯',
  '쓰다',
  '머리',
  '매우',
  '안',
  '좋아지다',
  '것',
  '같이',
  '아프다'],
 ['써다',
  '보신',
  '분',
  '들',
  '다',
  '들다',
  '알다',
  '겁니다',
  '용기',
  '허다',
  '접',
  '쓰기',
  '불편하다',
  '따로',
  '펌프',
  '용기',
  '하나',
  '구매',
  '옴겨',
  '담다',
  '쓰다'],
 ['샴푸',
  '향',
  '자체',
  '좀',
  '아저씨',
  '스킨',
  '냄새',
  '강하다',
  '샴푸',
  '손바닥',
  '덜',
  '때',
  '안',
  '내용',
  '가늠',
  '안되다',
  '많이',
  '나오다',
  '때',
  '펌프',
  '식이',
  '차라리',
  '좋다'],
 ['저', '같다', '경우', '머리', '피부', '예민하다', '피부', '트러블', '생기', '간지럽다'],
 ['탈모', '효과', '그닥', '모르다'],
 ['성분', '자체', '좋다', '못', '탈모', '걱정', '없이', '싸다', '맛', '쓸다', '불다', '추천', '드리다'],
 ['좋다',
  '기다',
  '그냥',
  '효과',
  '없음둥',
  '그냥',
  '사지',
  '말다',
  '욕',
  '나오다',
  '우리',
  '언제',
  '탈모',
  '벗어나다',
  '수'],
 ['가격', '조금', '부담', '되다'],
 ['머리', '뻣뻣하다', '두피', '건조하다', '지다'],
 ['약간', '자극', '적', '탈모', '방지', '효과', '탁월하다', '느낌', '없다'],
 ['개월', '이상', '써다', '때', '조금', '덜', '빠지다', '그', '이상', '효과', '못', '보다'],
 ['효과', '그닥', '자다', '모르다'],
 ['누르다',
  '펌프',
  '형',
  '아니다',
  '쭈욱',
  '짜다',
  '용기',
  '편리하다',
  '조금',
  '떨어지다',
  '모발',
  '굵다',
  '탈모',
  '도움',
  '직접',
  '적',
  '못',
  '주다',
  '같다'],
 ['없다'],
 ['일단', '단순', '샴푸', '토너', '탈모', '진행', '멈추다', '없다', '수', '없다'],
 ['모발',
  '굵다',
  '탈모',
  '기능',
  '없다',
  '것',
  '같다',
  '모발',
  '빳빳',
  '린스',
  '필수',
  '사용',
  '또한',
  '향',
  '좋다',
  '편',
  '오래',
  '지속',
  '되다',
  '않다'],
 ['냄새', '그닥'],
 ['양', '적다'],
 ['머리', '감', '때', '모발', '빳빳해', '느낌', '들다', '끊어지다', '아니다', '걱정', '되다'],
 ['머리', '말리다', '뒤', '뻣뻣하다', '느낌'],
 ['그다지', '효과', '모르다', '사용', '때'],
 ['근데',
  '머리',
  '덜',
  '빠지다',
  '않다',
  '같다',
  '빠지다',
  '양도',
  '똑같다',
  '효과',
  '닥',
  '같다',
  '애'],
 ['탈모',
  '유발',
  '성분',
  '탈모',
  '샴푸',
  '들어가다',
  '이해',
  '안감',
  '해외',
  '직구',
  '반값',
  '안',
  '가격',
  '구매'],
 ['구입',
  '매일',
  '아니다',
  '지속',
  '적',
  '계속',
  '사용',
  '탈모',
  '예방',
  '효과',
  '아직',
  '자다',
  '모르다'],
 ['병', '사용', '해봤다', '모발', '뿐', '아니다', '두피', '깨끗해지다', '느낌', '못', '받다'],
 ['샴푸',
  '사실',
  '탈모',
  '방지',
  '별로',
  '영향',
  '못',
  '주다',
  '먹다',
  '약',
  '제일',
  '낫다',
  '생각',
  '듭니'],
 ['비싸다'],
 ['가격', '조금', '비싸다'],
 ['사용',
  '후',
  '미녹시딜',
  '뿌리다',
  '때',
  '두피',
  '따끔',
  '거리',
  '아프다',
  '중단',
  '모발',
  '좋다',
  '장기간',
  '사용',
  '않다',
  '느끼다',
  '못',
  '확신',
  '건',
  '두피',
  '좋다',
  '것',
  '같다',
  '않다',
  '제',
  '두피',
  '약하다',
  '민감하다',
  '그래도',
  '미녹시딜',
  '뿌리다',
  '때',
  '상처',
  '소독',
  '처럼',
  '아프다',
  '삼',
  '푸다',
  '생각',
  '독하다',
  '같다'],
 ['한번', '사용', '후', '재', '구입', '안함', '푸석푸석하다', '느낌', '들어서다', '선호', '않다'],
 ['마릿결', '살짝', '푸석하다', '느낌', '잇다'],
 ['기', '달다', '점'],
 ['탈모',
  '방지',
  '효과',
  '글쎄',
  '탈모',
  '샴프',
  '많이',
  '써다',
  '보다',
  '샴프',
  '득',
  '본적',
  '없다',
  '그냥',
  '저기',
  '두피',
  '자다',
  '맞다',
  '거',
  '사용',
  '약',
  '권장'],
 ['독일', '사람', '머리'],
 ['탈모', '관', '효과', '자다', '모르다'],
 ['너무', '남성', '스킨', '향'],
 ['계속', '써다', '보다', '감고', '난후', '머리', '너무', '뻣뻣하다', '느낌', '강하다'],
 ['머리',
  '감다',
  '너무',
  '개털',
  '이',
  '되다',
  '머리',
  '끝',
  '부분',
  '엉킴',
  '생기다',
  '정도',
  '말리다',
  '때',
  '자다',
  '말리다',
  '야하다'],
 ['효과', '모르다'],
 ['광고',
  '입',
  '소문',
  '대비',
  '효과',
  '자다',
  '모르다',
  '우연히',
  '출장',
  '가기',
  '전',
  '페이스북',
  '광고',
  '보고',
  '대량',
  '사오다',
  '개월',
  '써다',
  '역시',
  '광고',
  '광고',
  '이다'],
 ['비싸다', '가격', '자극', '적', '발', '효과', '극미'],
 ['샴푸', '성분', '너무', '강하다'],
 ['너무', '물', '나오다', '탈모', '도움', '되다', '싶다', '약국', '사다', '가격', '비싸다'],
 ['일',
  '때',
  '대량',
  '구매',
  '하',
  '가격',
  '싸다',
  '평상시',
  '갑자기',
  '떨어지다',
  '구매',
  '때',
  '매장',
  '가격',
  '비싸다'],
 ['기분',
  '수도',
  '카페인',
  '흡수',
  '되다볻',
  '방',
  '늦다',
  '머리',
  '감다',
  '잠',
  '자다',
  '안',
  '오다',
  '느낌',
  '이다'],
 ['탈모', '개선', '자다', '모르다'],
 ['개인',
  '적',
  '향',
  '남성',
  '스킨',
  '향',
  '나서다',
  '조금',
  '그렇다',
  '탈모',
  '효과',
  '자다',
  '모르다'],
 ['정력', '때문', '사용', '아니다', '때문'],
 ['피부', '트러블', '발생'],
 ['뭔가', '깨끗해지다', '느낌', '실제', '효과', '못', '보다'],
 ['며릿결',
  '너무',
  '안',
  '좋아지다',
  '생각',
  '가격',
  '싸다',
  '않다',
  '점',
  '카페인',
  '성분',
  '게',
  '오히려',
  '좋다',
  '건지다',
  '나쁘다',
  '지도',
  '모르다',
  '제',
  '두피',
  '안',
  '맞다',
  '계속',
  '질',
  '질'],
 ['아빠', '스킨', '냄새', '나다'],
 ['탈모', '개선', '기대하다', '어렵다'],
 ['한국', '구', '때', '가격', '조금', '비싸다', '것', '같다'],
 ['재다', '의사', '없다'],
 ['남', '주다', '써다', '돈', '주다', '사서', '쓰다', '안', '살다', '같다'],
 ['모발', '힘', '생기', '기다', '빠지다', '막다', '못', '같다'],
 ['딱하다', '없다', '그냥', '효과', '뚜렷하다', '않다'],
 ['액', '상이', '너무', '쉬다', '흐르다'],
 [],
 ['별다르다', '문제점', '없다', '것', '같다'],
 ['조금', '비싸다'],
 ['눈', '띄다', '몸', '느끼다', '효과', '없다', '것', '같다'],
 ['탈모',
  '별로',
  '효과',
  '없다',
  '것',
  '같다',
  '향',
  '요즘',
  '젊다',
  '사람',
  '들',
  '좋아하다',
  '향',
  '아니다',
  '것',
  '같다'],
 ['향기', '취향', '많이', '탈', '것', '같다', '머리', '빳빳해', '것', '심하다', '너무', '불편하다'],
 ['뚜껑', '펌프', '방식', '아니다', '불편하다'],
 ['삼', '푸다', '후', '뻣뻣하다'],
 ['머리카락', '약간', '뻣뻣하다', '느낌'],
 ['제품군', '들', '다양하다', '나오다', '보다', '선택', '장애', '옴'],
 ['용량', '대비', '가격', '확실하다', '아쉽다'],
 ['샴푸', '보틀', '자체', '문제', '샴푸', '짤때', '양', '너무', '많이', '흘러나오다', '애', '먹다'],
 ['저', '다', '머리', '덜', '빠지다', '부가', '적', '효과', '없다', '같다'],
 ['효과', '없다'],
 ['실제', '발', '효과', '없다', '거', '같다'],
 ['효과', '모르다'],
 ['이상', '두피', '마사지', '두통', '생기다'],
 ['장기간', '쓰다', '머리', '약간', '뻣뻣하다', '느낌'],
 ['약간', '자극', '적', '피부', '민감하다', '사람', '들', '호불호', '갈릴', '수'],
 ['효과', '딱하다', '못', '느끼다'],
 ['탈묘효괴', '모르다'],
 ['거', '쓰다', '머리', '시원하다'],
 ['펌핑', '용기', '아니다', '손', '용기', '짜다', '써다', '해'],
 ['효과', '따로', '느끼다', '못'],
 ['탈모', '개선', '안되다'],
 ['냄새', '별로', '임'],
 ['거품', '복불복', '크게', '효과', '못', '보다'],
 ['다만', '가격', '조금', '비싸다', '같다'],
 ['향', '별로', '이다', '이미', '시작', '되다', '탈모', '개선', '효과', '볼', '수', '없다'],
 ['무', '적다'],
 ['거품', '자다', '안', '나다'],
 ['제품', '들', '같이', '머리', '빠지다'],
 ['머리', '덜', '빠지다', '느낌', '딱하다', '없다'],
 [],
 ['샘', '푸다', '너무', '너무', '좋다'],
 ['향', '너무', '아쉽다', '받다', '생각'],
 ['탈모', '자체', '효과', '성은', '그닥'],
 ['막상', '탈모', '효과'],
 ['지속', '적', '사용', '도움', '되다', '느낌'],
 [],
 ['효과', '잘', '모르다', '비싸다'],
 ['때때로', '두피', '뜨겁다', '느껴지다'],
 ['생각', '기름', '짐', '빠르다'],
 ['항상', '샴푸', '탈모', '효과', '미비하다', '점'],
 ['저', '같다', '경우', '머리', '뭐', '나다', '뾰', '루지', '같다'],
 ['딱하다', '없다', '부드럽다', '않다'],
 ['모발', '푸석하다', '느낌', '이다'],
 ['머릿결', '많이', '상하', '느낌', '이다', '푸석푸석'],
 ['꾸준하다', '써다', '보다', '효과', '크게', '모르다'],
 ['물', '같다', '거품', '자다', '안나', '기다리다', '해', '샴푸', '아저씨', '냄새', '남'],
 ['샴푸', '너무', '물', '나오다', '효과', '잘', '모르다'],
 ['그닥', '효과', '보다', '그래도', '향', '맘', '들다', '한동안', '사용', '제품'],
 ['머리', '떡', '경향', '뻣뻣하다', '짐'],
 ['기대', '많이', '탈모', '예방', '크게', '되다', '것', '같다', '않다'],
 ['가격', '좀', '비싸다'],
 ['효과', '자다', '모루', '겠다'],
 ['다른', '제품', '들', '비', '가격', '비싸다'],
 ['효과', '없다', '더', '쓰기', '아깝다', '움'],
 ['두피', '맞다', '함', '쓰다', '두피', '안', '맞다', '그냥', '헤드', '숄더', '쓰다'],
 ['딱하다', '체감', '되다', '정도', '탈모', '방지', '효과', '없다'],
 ['기대', '왜', '광고'],
 ['향', '별로', '같다', '메'],
 ['남자', '스킨', '향', '향', '호불호'],
 ['슈퍼', '안', '파다', '구매', '시', '번거롭다', '움', '정도'],
 ['탈모',
  '치료',
  '효과',
  '모르다',
  '샴푸',
  '본연',
  '기능',
  '떨어지다',
  '두피',
  '아침',
  '감다',
  '오후',
  '떡',
  '지다'],
 ['양', '비다', '비싸다', '효과', '미비하다'],
 ['양', '작다', '조금', '아쉽다'],
 ['용기', '별로', '딱하다', '탈모', '도움', '되다', '느낌', '없다'],
 ['머리', '너무', '뻣뻣하다', '짐'],
 ['시원하다', '점', '느껴지다', '않다'],
 ['짜다', '많이', '나오다', '때', '별로', '이다', '최근', '대형', '나오다', '자다', '쓰다', '쓰다'],
 ['머릿결', '많이', '뻣뻣하다', '오히려', '두피', '안좋다', '것', '같다'],
 ['향', '별로', '효과', '자다'],
 ['향', '남자', '스킨', '향', '같다', '목욕탕', '남자', '스킨', '향'],
 ['근데', '그거', '저', '느끼다', '없다'],
 ['별다르다', '장점', '자다', '모르다'],
 ['효과', '자다', '모르다', '습니'],
 ['옛날', '광고', '보고', '바로', '구매', '뭐라다', '크게', '오다', '닿다', '않다'],
 ['아빠', '스킨', '냄새'],
 ['냄새', '아빠', '스킨', '냄새'],
 ['거품', '자다', '안나'],
 ['효과', '자다', '모르다'],
 ['저', '탈모', '완화', '효과', '보지', '못'],
 ['효과', '크다', '않다', '같다', '다른', '것', '갈아타다'],
 ['거품', '잘나다', '성분', '두피', '좋다'],
 ['무난', '무난', '해', '탈모', '효과', '자다'],
 [],
 ['거품', '많이', '안나', '약품', '같다', '느낌'],
 ['좋다', '점', '아직', '못', '찾다'],
 [],
 ['머리', '감다', '이르다', '시간', '내', '냄새', '나다', '저', '잘', '안', '맞다'],
 ['약품', '머리', '바르다', '느낌', '랄', '끄다'],
 ['먹다', '바르다', '약품', '대비', '효과', '느껴지다', '않다'],
 ['다만', '향', '블루클럽', '민트', '샴푸', '비슷하다', '향', '나서다', '살짝'],
 ['샴푸', '기다리다', '야하다', '점'],
 ['실제', '굵다', '않다'],
 ['향', '개인', '적', '좋다', '않다'],
 ['광고', '너무', '많이', '나오다', '의심'],
 ['머리',
  '더',
  '빠지다',
  '것',
  '완화',
  '시키다',
  '같다',
  '머리카락',
  '너무',
  '뻣뻣하다',
  '느낌',
  '가늘어지다',
  '모발',
  '개선',
  '한계',
  '보이다'],
 ['것', '실제', '숱', '늘어나다', '않다'],
 ['탈모', '및', '발모', '효과', '미약', '듯'],
 ['제품', '가격', '면', '좀', '비싸다'],
 ['발', '효과', '확인', '불가능'],
 ['냄새', '무슨', '아저씨', '진하다', '스킨', '냄새', '머리', '결', '빳빳'],
 ['향', '때문', '두피', '자극', '느끼다'],
 ['딱하다', '두피', '뭐', '좋다', '건지다', '모르다'],
 ['탈모', '효과', '확실하다', '모르다'],
 ['가격', '비다', '양', '많다', '모르다'],
 ['발', '효과', '그닥', '못', '느끼다'],
 ['효과', '자다', '모르다'],
 ['효과', '없다', '같다'],
 ['효과', '모르다', '관리', '차원', '쓰다', '나쁘다', '않다', '것', '같다'],
 [],
 ['탈모', '도움', '될런', '모르다'],
 ['해외', '넘어오다', '비싸다', '탈모', '죽이다', '상품', '임'],
 ['탈모', '대한', '효과', '크게', '못', '느끼다'],
 ['머리', '빠지다', '막다', '그렇다', '효과', '없다'],
 ['냄새', '목욕탕', '향수', '냄새', '남'],
 ['향', '좀', '독하다', '같다'],
 ['계면활성제', '성분', '많다', '듣다'],
 ['다른',
  '샴푸',
  '들',
  '다르다',
  '기다리다',
  '점',
  '조금',
  '불편하다',
  '사용',
  '후',
  '머리',
  '결',
  '빳빳',
  '왁스',
  '손질',
  '시',
  '손질',
  '자다',
  '되게',
  '해주다'],
 ['탈모', '예방', '효과', '모르다'],
 ['향', '너무', '너무', '별로', '이다'],
 ['가격',
  '만',
  '않다',
  '효과',
  '거의',
  '없다',
  '선물',
  '받다',
  '쓰다',
  '제',
  '돈',
  '구입',
  '의사',
  '없다'],
 ['삼', '푸다', '류', '한계', '그닥효', '없다'],
 ['가격', '대비', '양', '적다', '거품', '적다'],
 ['오래', '써다', '그렇다', '모르다', '특별하다', '좋다', '점도', '모르다', '적어도', '악화시키다', '않다'],
 ['사실', '항기', '없다', '삼', '푸다', '냄새'],
 ['너무',
  '남자',
  '스키',
  '냄새',
  '심하다',
  '가격',
  '대비',
  '양',
  '적다',
  '한때',
  '티비',
  '광고',
  '엄청',
  '써다',
  '봄'],
 ['써다', '보다', '그닥', '구렇더', '냄새', '효과'],
 ['남자', '스킨', '향', '향', '때문', '손', '자다', '가지', '않다'],
 ['용감', '무엇', '익숙', '치', '않다', '아쉽다'],
 ['불쓰원삿',
  '떠오르다',
  '모양',
  '색깔',
  '스며들다',
  '양치',
  '동안',
  '안',
  '씻다',
  '내다',
  '아무래도',
  '독하다',
  '해',
  '뭔가',
  '가늘어지다',
  '느낌',
  '요즘',
  '감고',
  '바로',
  '씻다',
  '내다'],
 ['아쉬움', '점', '딱하다', '없다'],
 ['말', '그대로', '의약품', '냄새', '샴푸', '향', '기대하다', '좀', '어리다', '같다'],
 ['샴푸', '모발', '힘', '없다', '스타', '일링', '좀', '불편하다'],
 ['향', '맘', '안', '들다'],
 ['향', '럭'],
 [],
 ['가격', '비싸다'],
 ['아쉽다',
  '점',
  '이',
  '샴푸',
  '머리',
  '감다',
  '엄청',
  '빳빳',
  '거',
  '그래서',
  '이중',
  '저',
  '다른',
  '샴푸',
  '머리',
  '번',
  '더',
  '감고',
  '트리',
  '트먼트',
  '특히',
  '트리',
  '트먼트할',
  '때',
  '엄청',
  '빠지다',
  '샴푸',
  '써다',
  '결국',
  '트리트먼트',
  '때',
  '빠지다',
  '좋다',
  '건지다',
  '나쁘다',
  '건지다',
  '모르다'],
 ['향',
  '맘',
  '안',
  '들다',
  '좀',
  '향',
  '긋다',
  '향',
  '나몀',
  '좋다',
  '말로',
  '형용',
  '수',
  '없다',
  '냄새',
  '그건',
  '좀',
  '맘',
  '안',
  '듭니',
  '거',
  '쓰다',
  '정수리',
  '냄새',
  '맡다',
  '정수리',
  '냄새',
  '그대로',
  '날',
  '거',
  '같다'],
 ['머리카락', '굵다', '느낌', '받다', '못'],
 ['이',
  '샴푸',
  '쓰다',
  '머리',
  '축',
  '처지',
  '힘',
  '없어지다',
  '또',
  '냄새',
  '개인',
  '적',
  '역',
  '느껴지다'],
 ['머리카락', '뻣뻣하다', '느껴지다', '기름기', '아예', '쏙', '빠지다', '버리다'],
 ['사용', '후', '모발', '조금', '뻣뻣하다', '느낌', '듭니'],
 ['효과', '모르다'],
 ['모발', '힘', '살짝', '없어지다', '것', '같다'],
 ['매일', '쓰다', '보다', '쿨링감', '안', '느껴지다', '같다'],
 ['나다', '빳빳함', '피자', '극'],
 ['머리', '좀', '뻣뻣', '엉킴'],
 ['가격', '좀', '비싸다', '그닥', '크다', '효과', '보기', '어렵다'],
 ['과연', '효과', '의문'],
 ['좋다', '점', '참고'],
 ['탈모', '효과', '적', '인지'],
 ['나쁘다', '점', '랄', '것', '못', '찾다'],
 ['연모', '화', '진행중', '이기다', '좀', '힘', '없이', '치다', '느낌'],
 ['다만', '어느', '샴푸', '그렇다', '기적', '적', '효과', '없다', '것', '같다'],
 ['쓰다', '조금', '건조하다'],
 [],
 ['지루', '성', '두피', '가려움', '여전하다'],
 ['지루', '성', '두피', '효가', '없다', '같다'],
 ['두피', '가렵', '비듬', '많이', '생기다', '진짜', '비추다'],
 ['제일', '중요하다', '제', '자신', '맞다', '않다', '뾰루지', '나다'],
 ['모발', '힘', '강하다', '붙다', '않다', '간지럽다', '움', '효과', '강하다', '않다'],
 ['쓰다', '불편하다', '점', '없다'],
 ['시원하다', '느낌', '싫어하다', '사람', '들', '별로', '일수'],
 ['테',
  '살짝',
  '머리',
  '뻣뻣하다',
  '감',
  '날',
  '괜찮다',
  '너무',
  '오래',
  '머리',
  '감다',
  '뻣뻣하다',
  '같다'],
 ['향', '멘솔', '느낌', '머리', '감다', '머릿결', '빗자루', '빳빳해'],
 ['가격', '좀', '아쉽다', '일', '때', '쟁여놓'],
 ['가격', '대가', '알짝', '아쉽다'],
 ['딱하다',
  '없다',
  '굳이',
  '뽑다',
  '향기',
  '매우',
  '약하다',
  '상쾌하다',
  '향',
  '나다',
  '시간',
  '조금',
  '지나다',
  '향'],
 ['딱하다', '없다', '같다'],
 ['효과', '것', '같다', '가격', '확실하다', '비싸다', '것', '같다'],
 ['제',
  '두피',
  '반나절',
  '지나',
  '기름기',
  '자다',
  '올라오다',
  '그래서',
  '재다',
  '매다',
  '안',
  '것',
  '같다'],
 ['다만', '가격', '아쉽다', '좀', '비싸다'],
 ['실리콘',
  '성분',
  '안',
  '들다',
  '실리콘',
  '성분',
  '들다',
  '것',
  '밉다',
  '끌',
  '밉다',
  '끈',
  '거리',
  '것',
  '같다',
  '머리',
  '이전',
  '써다',
  '성용',
  '샴푸',
  '빨리',
  '기르다',
  '처음',
  '써다',
  '때',
  '정력',
  '약간',
  '떨어지다',
  '지다',

In [177]:
len(bad_tokens)

5739

In [179]:
cont_id2word = corpora.Dictionary(cont_tokens)
cont_corpus = [cont_id2word.doc2bow(text) for text in cont_tokens]

In [180]:
good_id2word = corpora.Dictionary(good_tokens)
good_corpus = [good_id2word.doc2bow(text) for text in good_tokens]

In [181]:
bad_id2word = corpora.Dictionary(bad_tokens)
bad_corpus = [bad_id2word.doc2bow(text) for text in bad_tokens]

In [101]:
import pyLDAvis.gensim
import pickle
import pyLDAvis
import os

In [182]:
num_topics = 5
lda_model5 = gensim.models.LdaMulticore(corpus=cont_corpus,id2word=cont_id2word,num_topics=num_topics,iterations=500)
doc_lda = lda_model5[cont_corpus]

pyLDAvis.enable_notebook()
vis = pyLDAvis.gensim.prepare(lda_model5,cont_corpus,cont_id2word)
pyLDAvis.display(vis)

In [122]:
num_topics = 6
lda_model6 = gensim.models.LdaMulticore(corpus=cont_corpus,id2word=cont_id2word,num_topics=num_topics,iterations=500)
doc_lda = lda_model6[cont_corpus]

pyLDAvis.enable_notebook()
vis = pyLDAvis.gensim.prepare(lda_model6,cont_corpus,cont_id2word)
pyLDAvis.display(vis)

In [190]:
num_topics = 7
lda_model7 = gensim.models.LdaMulticore(corpus=cont_corpus,id2word=cont_id2word,num_topics=num_topics,iterations=500)
doc_lda = lda_model7[cont_corpus]

pyLDAvis.enable_notebook()
vis = pyLDAvis.gensim.prepare(lda_model7,cont_corpus,cont_id2word)
pyLDAvis.display(vis)

In [227]:
def make_topictable(ldamodel,corpus):
    rows = []
    # topic_table = pd.DataFrame()
    for i, topic_list in enumerate(ldamodel[corpus]):
        doc = topic_list[0] if ldamodel.per_word_topics else topic_list
        doc = sorted(doc, key=lambda x: (x[1]), reverse = True)
        # for j, (topic_num, prop_topic) in enumerate(doc):
        #     if j == 0:
        #         topic_table = pd.concat([topic_table,pd.Series([int(topic_num),round(prop_topic,4),topic_list])],ignore_index=True)
        #     else:
        #         break
        for j, (topic_num, prop_topic) in enumerate(doc):
            if j == 0:
                row = [int(topic_num), round(prop_topic, 4), topic_list]
                rows.append(row)
    
    topic_table = pd.concat([pd.Series(row) for row in rows], axis=1).T
    # topic_table.columns = ['Topic_Num', 'Prop_Topic', 'Topic_List']
    return(topic_table)

In [191]:
cont_lda_model = lda_model7

In [229]:
cont_topictable = make_topictable(cont_lda_model,cont_corpus)
cont_topictable
cont_topictable.reset_index()
cont_topictable.columns = ['문서 번호','가장 비중이 높은 토픽의 비중','각 토픽의 비중']
cont_topictable
# topictable = topictable.reset_index()
# topictable.columns =

    문서 번호 가장 비중이 높은 토픽의 비중                                           각 토픽의 비중
0       4           0.8566  [(0, 0.023957323), (1, 0.02386534), (2, 0.0239...
1       5           0.8567  [(0, 0.023860294), (1, 0.023860116), (2, 0.023...
2       2           0.9547                                    [(2, 0.954702)]
3       1           0.7851  [(0, 0.035773713), (1, 0.7850679), (2, 0.03578...
4       4            0.914  [(0, 0.014322489), (1, 0.014334685), (2, 0.014...
..    ...              ...                                                ...
911     4            0.714  [(0, 0.04765368), (1, 0.047642414), (2, 0.0476...
912     3           0.9427                                  [(3, 0.94270885)]
913     2           0.9944                                   [(2, 0.9944483)]
914     3           0.9761                                   [(3, 0.9760916)]
915     1           0.9386  [(0, 0.010241366), (1, 0.938583), (2, 0.010253...

[916 rows x 3 columns]

In [185]:
num_topics = 8
lda_model8 = gensim.models.LdaMulticore(corpus=cont_corpus,id2word=cont_id2word,num_topics=num_topics,iterations=500)
doc_lda = lda_model8[cont_corpus]

pyLDAvis.enable_notebook()
vis = pyLDAvis.gensim.prepare(lda_model8,cont_corpus,cont_id2word)
pyLDAvis.display(vis)

In [119]:
num_topics = 9
lda_model9 = gensim.models.LdaMulticore(corpus=cont_corpus,id2word=cont_id2word,num_topics=num_topics,iterations=500)
doc_lda = lda_model9[cont_corpus]

pyLDAvis.enable_notebook()
vis = pyLDAvis.gensim.prepare(lda_model9,cont_corpus,cont_id2word)
pyLDAvis.display(vis)

In [106]:
num_topics = 10
lda_model10 = gensim.models.LdaMulticore(corpus=cont_corpus,id2word=cont_id2word,num_topics=num_topics,iterations=500)
doc_lda = lda_model10[cont_corpus]

pyLDAvis.enable_notebook()
vis = pyLDAvis.gensim.prepare(lda_model10,cont_corpus,cont_id2word)
pyLDAvis.display(vis)

In [194]:
num_topics = 5
good_model = gensim.models.LdaMulticore(corpus=good_corpus,id2word=good_id2word,num_topics=num_topics,iterations=500)
doc_lda = good_model[good_corpus]

pyLDAvis.enable_notebook()
vis = pyLDAvis.gensim.prepare(good_model,good_corpus,good_id2word)
pyLDAvis.display(vis)

In [224]:
num_topics = 6
good_model2 = gensim.models.LdaMulticore(corpus=good_corpus,id2word=good_id2word,num_topics=num_topics,iterations=500)
doc_lda = good_model2[good_corpus]

pyLDAvis.enable_notebook()
vis = pyLDAvis.gensim.prepare(good_model2,good_corpus,good_id2word)
pyLDAvis.display(vis)

In [228]:
good_topictable = make_topictable(good_model2,good_corpus)
good_topictable.reset_index()
good_topictable.columns = ['문서 번호','가장 비중이 높은 토픽의 비중','각 토픽의 비중']
good_topictable
# topictable = topictable.reset_index()
# topictable.columns =

     문서 번호 가장 비중이 높은 토픽의 비중                                           각 토픽의 비중
0        0           0.9935                                  [(0, 0.99347997)]
1        3           0.9847                                   [(3, 0.9846592)]
2        5           0.5424                  [(3, 0.42953652), (5, 0.5423631)]
3        2           0.9852                                   [(2, 0.9851987)]
4        4           0.9844                                   [(4, 0.9843982)]
...    ...              ...                                                ...
9869     3           0.8946  [(0, 0.021041287), (1, 0.021071786), (2, 0.021...
9870     2           0.8795  [(0, 0.024082024), (1, 0.024048617), (2, 0.879...
9871     4            0.831  [(0, 0.033727035), (1, 0.033743743), (2, 0.033...
9872     2           0.8314  [(0, 0.033679746), (1, 0.03383373), (2, 0.8314...
9873     4           0.8594  [(0, 0.028076753), (1, 0.028225856), (2, 0.028...

[9874 rows x 3 columns]

In [232]:
num_topics = 7
bad_model = gensim.models.LdaMulticore(corpus=bad_corpus,id2word=bad_id2word,num_topics=num_topics,iterations=500)
doc_lda = bad_model[bad_corpus]

pyLDAvis.enable_notebook()
vis = pyLDAvis.gensim.prepare(bad_model,bad_corpus,bad_id2word)
pyLDAvis.display(vis)

In [246]:
num_topics = 9
bad_model2 = gensim.models.LdaMulticore(corpus=bad_corpus,id2word=bad_id2word,num_topics=num_topics,iterations=500)
doc_lda = bad_model2[bad_corpus]

pyLDAvis.enable_notebook()
vis = pyLDAvis.gensim.prepare(bad_model2,bad_corpus,bad_id2word)
pyLDAvis.display(vis)

In [248]:
bad_topictable = make_topictable(bad_model2,bad_corpus)
bad_topictable.reset_index()
bad_topictable.columns = ['문서 번호','가장 비중이 높은 토픽의 비중','각 토픽의 비중']
bad_topictable
# topictable = topictable.reset_index()
# topictable.columns =

     문서 번호 가장 비중이 높은 토픽의 비중                                           각 토픽의 비중
0        1           0.9738                                  [(1, 0.97384095)]
1        5           0.7119                 [(5, 0.71185887), (7, 0.24233761)]
2        1           0.9738                                  [(1, 0.97384083)]
3        7            0.796                  [(0, 0.18455222), (7, 0.7959838)]
4        4           0.7035  [(0, 0.037062634), (1, 0.037055537), (2, 0.037...
...    ...              ...                                                ...
5734     2           0.8729  [(0, 0.015879462), (1, 0.015887208), (2, 0.872...
5735     0           0.8729  [(0, 0.87293535), (1, 0.015883282), (2, 0.0158...
5736     4           0.9012  [(0, 0.012351962), (1, 0.012351288), (2, 0.012...
5737     4           0.7777  [(0, 0.027782874), (1, 0.027783778), (2, 0.027...
5738     6           0.8517  [(0, 0.018532246), (1, 0.018537547), (2, 0.018...

[5739 rows x 3 columns]

In [260]:
drop_df

,href,title,reviewNum,tag,brand,company,howToUse,ingredients,image,volume,...,commentBad,contentTopic,contentTopicPerc,contentTopicDist,goodTopic,goodTopicPerc,goodTopicDist,badTopic,badTopicPerc,badTopicDist
0,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,"스댕 용기 개 이쁘고 좋은데, 원가 너무 비싸서 내가 보기에는 가격이 높은 최대 ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16703,https://daedamo.com/ingre/99?sca=탈모관련상품&overla...,\n 니심 건성모발용 샴푸,0.0,두피샴푸,니심,니옥신,두피와 모발 전체를 마사지 하듯이 1분가량 꼼꼼하게 샴푸하고 미온수로 씻어냅니다. ...,"정제수, 소듐C14-16올레핀설포네이트, 소듐코코암포아세테이트, 피이지-4레이프씨다...",https://daedamo.com/new/data/file/ingre/179434...,240ml,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16704,https://daedamo.com/ingre/82?sca=탈모관련상품&overla...,\n 트리코민 덴시파잉 샴푸,0.0,두피샴푸,트리코민,니옥신,거품을 충분히 내신 후 바로 헹구지 마시고 3-5분 가량 그대로 두어 영양성분이 충...,"정제수, 알로에베라잎즙, 에키네시하추출물, 아이소말트, 완두싹추출물, 하이드롤라이즈...",https://daedamo.com/new/data/file/ingre/179434...,177.4ml,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16705,https://daedamo.com/ingre/80?sca=탈모관련상품&overla...,\n 드림헤어 순간증모제 전용 미스트,0.0,스타일링,드림헤어,니옥신,증모제를 사용하신후 본 제품을 직접적으로 분사하지 마시고 머리위 하늘에 뿌려주듯 분...,"에탄올, 정제수, 아크릴레이트/옥틸아크릴아마이드코폴리머, 녹차추출물, 곰솔잎추출물,...",https://daedamo.com/new/data/file/ingre/179434...,150ml,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16706,https://daedamo.com/ingre/75?sca=탈모관련상품&overla...,\n 드림헤어 블랙시크릿(휴대용),0.0,헤어커버,드림헤어,니옥신,증모제를 도포후 두피쪽에 증착될 수 있도록 머리를 쓰다듬듯이 살살 털어줍니다.,"레이온, 폴라아마이드, 비오틴, 실크펩타이드, 카퍼트리펩타이드, 대두레시틴, 헤나추출물",https://daedamo.com/new/data/file/ingre/179434...,7g,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16707,https://daedamo.com/ingre/74?sca=탈모관련상품&overla...,\n 드림헤어 순간증모제,0.0,헤어커버,드림헤어,니옥신,증모제를 도포후 두피쪽에 증착될 수 있도록 머리를 쓰다듬듯이 살살 털어줍니다.,"레이온, 폴리아마이드, 비오틴, 실크펩타이드, 카퍼트리펩타이드, 대두레시틴, 헤나추출물",https://daedamo.com/new/data/file/ingre/179434...,23g,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [267]:
drop_df['contentTopicPerc'] = np.nan
drop_df['contentTopicDist'] = np.nan
drop_df['goodTopic'] = np.nan
drop_df['goodTopicPerc'] = np.nan
drop_df['goodTopicDist'] = np.nan
drop_df['badTopic'] = np.nan
drop_df['badTopicPerc'] = np.nan
drop_df['badTopicDist'] = np.nan

# drop_df = drop_df.drop(columns='contentTopic',axis=1)
drop_df.drop(columns = ['href','title','reviewNum','tag','brand','company','ingredients','image','volume','price','totalScore'])

,howToUse,satisfactionScore,priceScore,rebuyScore,commenter,commentDate,commentContent,commentGood,commentBad,contentTopic,contentTopicPerc,contentTopicDist,goodTopic,goodTopicPerc,goodTopicDist,badTopic,badTopicPerc,badTopicDist
0,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,80%,80%,100%,K2646350517,3달 전,NaN,"앞머리 모발이식 13년전에 하고는 프로스카 띄엄띄엄 먹었는데, 정수리 광탈 시작...","스댕 용기 개 이쁘고 좋은데, 원가 너무 비싸서 내가 보기에는 가격이 높은 최대 ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,NaN,NaN,NaN,a337*****,한 시간 전,탈모라 써봤는데 시원하고 좋아요,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,NaN,NaN,NaN,suwo******,하루 전,머리감을때마다 시원하고좋아요,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,NaN,NaN,NaN,wall***,하루 전,전에 쿨샴푸를 한번썻는데 맘에들어서 다른색으로 하나 더 주문했습니다. 샘플 사은품...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,NaN,NaN,NaN,zzzz****,2일 전,아주좋습니다좋아요~,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16703,두피와 모발 전체를 마사지 하듯이 1분가량 꼼꼼하게 샴푸하고 미온수로 씻어냅니다. ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16704,거품을 충분히 내신 후 바로 헹구지 마시고 3-5분 가량 그대로 두어 영양성분이 충...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16705,증모제를 사용하신후 본 제품을 직접적으로 분사하지 마시고 머리위 하늘에 뿌려주듯 분...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16706,증모제를 도포후 두피쪽에 증착될 수 있도록 머리를 쓰다듬듯이 살살 털어줍니다.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16707,증모제를 도포후 두피쪽에 증착될 수 있도록 머리를 쓰다듬듯이 살살 털어줍니다.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [273]:
contentTopic = cont_topictable['문서 번호']
contentTopicPerc = cont_topictable['가장 비중이 높은 토픽의 비중']
contentTopicDist = cont_topictable['각 토픽의 비중']

goodTopic = good_topictable['문서 번호']
goodTopicPerc = good_topictable['가장 비중이 높은 토픽의 비중']
goodTopicDist = good_topictable['각 토픽의 비중']

badTopic = bad_topictable['문서 번호']
badTopicPerc = bad_topictable['가장 비중이 높은 토픽의 비중']
badTopicDist = bad_topictable['각 토픽의 비중']

916

In [289]:
contentTopicDist[0]

[(0, 0.023957323),
 (1, 0.02386534),
 (2, 0.023919415),
 (3, 0.023868967),
 (4, 0.856599),
 (5, 0.023906127),
 (6, 0.023883833)]

In [342]:
cont_hrefs = drop_df[drop_df['tag'].apply(lambda x: str(x)=='두피샴푸' or str(x)=='탈모샴푸')][drop_df['commentContent'].notnull()]['href'].reset_index()
cont_commenter = drop_df[drop_df['tag'].apply(lambda x: str(x)=='두피샴푸' or str(x)=='탈모샴푸')][drop_df['commentContent'].notnull()]['commenter'].reset_index()
cont_comment = drop_df[drop_df['tag'].apply(lambda x: str(x)=='두피샴푸' or str(x)=='탈모샴푸')][drop_df['commentContent'].notnull()]['commentContent'].reset_index()

good_hrefs = drop_df[drop_df['tag'].apply(lambda x: str(x)=='두피샴푸' or str(x)=='탈모샴푸')][drop_df['commentGood'].notnull()]['href'].reset_index()
good_commenter = drop_df[drop_df['tag'].apply(lambda x: str(x)=='두피샴푸' or str(x)=='탈모샴푸')][drop_df['commentGood'].notnull()]['commenter'].reset_index()
good_comment = drop_df[drop_df['tag'].apply(lambda x: str(x)=='두피샴푸' or str(x)=='탈모샴푸')][drop_df['commentGood'].notnull()]['commentGood'].reset_index()

bad_hrefs = drop_df[drop_df['tag'].apply(lambda x: str(x)=='두피샴푸' or str(x)=='탈모샴푸')][drop_df['commentBad'].notnull()]['href'].reset_index()
bad_commenter = drop_df[drop_df['tag'].apply(lambda x: str(x)=='두피샴푸' or str(x)=='탈모샴푸')][drop_df['commentBad'].notnull()]['commenter'].reset_index()
bad_comment = drop_df[drop_df['tag'].apply(lambda x: str(x)=='두피샴푸' or str(x)=='탈모샴푸')][drop_df['commentBad'].notnull()]['commentBad'].reset_index()

# cont_hrefs = cont_hrefs.reset_index()
cont_hrefs
cont_commenter
# cont_comment

/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/3153998612.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  cont_hrefs = drop_df[drop_df['tag'].apply(lambda x: str(x)=='두피샴푸' or str(x)=='탈모샴푸')][drop_df['commentContent'].notnull()]['href'].reset_index()
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/3153998612.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  cont_commenter = drop_df[drop_df['tag'].apply(lambda x: str(x)=='두피샴푸' or str(x)=='탈모샴푸')][drop_df['commentContent'].notnull()]['commenter'].reset_index()
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/3153998612.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  cont_comment = drop_df[drop_df['tag'].apply(lambda x: str(x)=='두피샴푸' or str(x)=='탈모샴푸')][drop_df['commentContent'].notnull()]['commentContent'].reset_index()
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/3153998612.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  good_hrefs = drop_df[drop_df['tag'].apply(lambda x: str(x)=='두피샴푸' or str(x)=='탈모샴푸')][drop_df['commentGood'].notnull()]['href'].reset_index()
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/3153998612.py:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  good_commenter = drop_df[drop_df['tag'].apply(lambda x: str(x)=='두피샴푸' or str(x)=='탈모샴푸')][drop_df['commentGood'].notnull()]['commenter'].reset_index()
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/3153998612.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  good_comment = drop_df[drop_df['tag'].apply(lambda x: str(x)=='두피샴푸' or str(x)=='탈모샴푸')][drop_df['commentGood'].notnull()]['commentGood'].reset_index()
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/3153998612.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  bad_hrefs = drop_df[drop_df['tag'].apply(lambda x: str(x)=='두피샴푸' or str(x)=='탈모샴푸')][drop_df['commentBad'].notnull()]['href'].reset_index()
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/3153998612.py:10: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  bad_commenter = drop_df[drop_df['tag'].apply(lambda x: str(x)=='두피샴푸' or str(x)=='탈모샴푸')][drop_df['commentBad'].notnull()]['commenter'].reset_index()
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/3153998612.py:11: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  bad_comment = drop_df[drop_df['tag'].apply(lambda x: str(x)=='두피샴푸' or str(x)=='탈모샴푸')][drop_df['commentBad'].notnull()]['commentBad'].reset_index()

     index    commenter
0        1    a337*****
1        2   suwo******
2        3      wall***
3        4     zzzz****
4        5     sj05****
..     ...          ...
911   1171     bbho****
912   1172     ggod****
913   1173  love*******
914   1174     the7****
915   1175       78****

[916 rows x 2 columns]

In [316]:
cont_comment.index

RangeIndex(start=0, stop=916, step=1)

In [338]:
drop_df['goodTopic'] = None
drop_df['goodTopicPerc'] = None
drop_df['goodTopicDist'] = None
drop_df['badTopic'] = None
drop_df['badTopicPerc'] = None
drop_df['badTopicDist'] = None

/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/655073321.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drop_df['goodTopic'] = None
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/655073321.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drop_df['goodTopicPerc'] = None
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/655073321.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drop_df['goodTopicDist'] = None
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/655073321.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drop_df['badTopic'] = None
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/655073321.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drop_df['badTopicPerc'] = None
/var/folders/6w/c4b_62q127db3fwswnvnsm_c0000gn/T/ipykernel_39991/655073321.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drop_df['badTopicDist'] = None

In [339]:
drop_df

,href,title,reviewNum,tag,brand,company,howToUse,ingredients,image,volume,...,commentBad,contentTopic,contentTopicPerc,contentTopicDist,goodTopic,goodTopicPerc,goodTopicDist,badTopic,badTopicPerc,badTopicDist
0,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,"스댕 용기 개 이쁘고 좋은데, 원가 너무 비싸서 내가 보기에는 가격이 높은 최대 ...",None,None,None,None,None,None,None,None,None
1,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,NaN,4,0.8566,"[(0, 0.023957323), (1, 0.02386534), (2, 0.0239...",None,None,None,None,None,None
2,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,NaN,5,0.8567,"[(0, 0.023860294), (1, 0.023860116), (2, 0.023...",None,None,None,None,None,None
3,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,NaN,2,0.9547,"[(2, 0.954702)]",None,None,None,None,None,None
4,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,NaN,1,0.7851,"[(0, 0.035773713), (1, 0.7850679), (2, 0.03578...",None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16703,https://daedamo.com/ingre/99?sca=탈모관련상품&overla...,\n 니심 건성모발용 샴푸,0.0,두피샴푸,니심,니옥신,두피와 모발 전체를 마사지 하듯이 1분가량 꼼꼼하게 샴푸하고 미온수로 씻어냅니다. ...,"정제수, 소듐C14-16올레핀설포네이트, 소듐코코암포아세테이트, 피이지-4레이프씨다...",https://daedamo.com/new/data/file/ingre/179434...,240ml,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16704,https://daedamo.com/ingre/82?sca=탈모관련상품&overla...,\n 트리코민 덴시파잉 샴푸,0.0,두피샴푸,트리코민,니옥신,거품을 충분히 내신 후 바로 헹구지 마시고 3-5분 가량 그대로 두어 영양성분이 충...,"정제수, 알로에베라잎즙, 에키네시하추출물, 아이소말트, 완두싹추출물, 하이드롤라이즈...",https://daedamo.com/new/data/file/ingre/179434...,177.4ml,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16705,https://daedamo.com/ingre/80?sca=탈모관련상품&overla...,\n 드림헤어 순간증모제 전용 미스트,0.0,스타일링,드림헤어,니옥신,증모제를 사용하신후 본 제품을 직접적으로 분사하지 마시고 머리위 하늘에 뿌려주듯 분...,"에탄올, 정제수, 아크릴레이트/옥틸아크릴아마이드코폴리머, 녹차추출물, 곰솔잎추출물,...",https://daedamo.com/new/data/file/ingre/179434...,150ml,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16706,https://daedamo.com/ingre/75?sca=탈모관련상품&overla...,\n 드림헤어 블랙시크릿(휴대용),0.0,헤어커버,드림헤어,니옥신,증모제를 도포후 두피쪽에 증착될 수 있도록 머리를 쓰다듬듯이 살살 털어줍니다.,"레이온, 폴라아마이드, 비오틴, 실크펩타이드, 카퍼트리펩타이드, 대두레시틴, 헤나추출물",https://daedamo.com/new/data/file/ingre/179434...,7g,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16707,https://daedamo.com/ingre/74?sca=탈모관련상품&overla...,\n 드림헤어 순간증모제,0.0,헤어커버,드림헤어,니옥신,증모제를 도포후 두피쪽에 증착될 수 있도록 머리를 쓰다듬듯이 살살 털어줍니다.,"레이온, 폴리아마이드, 비오틴, 실크펩타이드, 카퍼트리펩타이드, 대두레시틴, 헤나추출물",https://daedamo.com/new/data/file/ingre/179434...,23g,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [327]:
cont_hrefs

     index                                               href
0        1  https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...
1        2  https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...
2        3  https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...
3        4  https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...
4        5  https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...
..     ...                                                ...
911   1171  https://daedamo.com/ingre/27319?sca=탈모관련상품&ove...
912   1172  https://daedamo.com/ingre/27319?sca=탈모관련상품&ove...
913   1173  https://daedamo.com/ingre/27319?sca=탈모관련상품&ove...
914   1174  https://daedamo.com/ingre/27319?sca=탈모관련상품&ove...
915   1175  https://daedamo.com/ingre/27319?sca=탈모관련상품&ove...

[916 rows x 2 columns]

In [337]:
for i in cont_hrefs.index:
    condition = (drop_df['href'] == cont_hrefs['href'][i]) & (drop_df['commenter'] == cont_commenter['commenter'][i]) & (drop_df['commentContent'] == cont_comment['commentContent'][i])
    drop_df.loc[condition,'contentTopic'] = contentTopic[i]
    drop_df.loc[condition,'contentTopicPerc'] = contentTopicPerc[i]
    drop_df.loc[condition,'contentTopicDist'] = str(contentTopicDist[i])
drop_df.head()

,href,title,reviewNum,tag,brand,company,howToUse,ingredients,image,volume,...,priceScore,rebuyScore,commenter,commentDate,commentContent,commentGood,commentBad,contentTopic,contentTopicPerc,contentTopicDist
0,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,80%,100%,K2646350517,3달 전,NaN,"앞머리 모발이식 13년전에 하고는 프로스카 띄엄띄엄 먹었는데, 정수리 광탈 시작...","스댕 용기 개 이쁘고 좋은데, 원가 너무 비싸서 내가 보기에는 가격이 높은 최대 ...",None,None,None
1,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,NaN,NaN,a337*****,한 시간 전,탈모라 써봤는데 시원하고 좋아요,NaN,NaN,4,0.8566,"[(0, 0.023957323), (1, 0.02386534), (2, 0.0239..."
2,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,NaN,NaN,suwo******,하루 전,머리감을때마다 시원하고좋아요,NaN,NaN,5,0.8567,"[(0, 0.023860294), (1, 0.023860116), (2, 0.023..."
3,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,NaN,NaN,wall***,하루 전,전에 쿨샴푸를 한번썻는데 맘에들어서 다른색으로 하나 더 주문했습니다. 샘플 사은품...,NaN,NaN,2,0.9547,"[(2, 0.954702)]"
4,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,NaN,NaN,zzzz****,2일 전,아주좋습니다좋아요~,NaN,NaN,1,0.7851,"[(0, 0.035773713), (1, 0.7850679), (2, 0.03578..."

In [343]:
for i in good_hrefs.index:
    condition = (drop_df['href'] == good_hrefs['href'][i]) & (drop_df['commenter'] == good_commenter['commenter'][i]) & (drop_df['commentGood'] == good_comment['commentGood'][i])
    drop_df.loc[condition,'goodTopic'] = goodTopic[i]
    drop_df.loc[condition,'goodTopicPerc'] = goodTopicPerc[i]
    drop_df.loc[condition,'goodTopicDist'] = str(goodTopicDist[i])
drop_df.head()

,href,title,reviewNum,tag,brand,company,howToUse,ingredients,image,volume,...,commentBad,contentTopic,contentTopicPerc,contentTopicDist,goodTopic,goodTopicPerc,goodTopicDist,badTopic,badTopicPerc,badTopicDist
0,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,"스댕 용기 개 이쁘고 좋은데, 원가 너무 비싸서 내가 보기에는 가격이 높은 최대 ...",None,None,None,0,0.9935,"[(0, 0.9934807)]",None,None,None
1,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,NaN,4,0.8566,"[(0, 0.023957323), (1, 0.02386534), (2, 0.0239...",None,None,None,None,None,None
2,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,NaN,5,0.8567,"[(0, 0.023860294), (1, 0.023860116), (2, 0.023...",None,None,None,None,None,None
3,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,NaN,2,0.9547,"[(2, 0.954702)]",None,None,None,None,None,None
4,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,NaN,1,0.7851,"[(0, 0.035773713), (1, 0.7850679), (2, 0.03578...",None,None,None,None,None,None

In [344]:
for i in bad_hrefs.index:
    condition = (drop_df['href'] == bad_hrefs['href'][i]) & (drop_df['commenter'] == bad_commenter['commenter'][i]) & (drop_df['commentBad'] == bad_comment['commentBad'][i])
    drop_df.loc[condition,'badTopic'] = badTopic[i]
    drop_df.loc[condition,'badTopicPerc'] = badTopicPerc[i]
    drop_df.loc[condition,'badTopicDist'] = str(badTopicDist[i])
drop_df.head()

,href,title,reviewNum,tag,brand,company,howToUse,ingredients,image,volume,...,commentBad,contentTopic,contentTopicPerc,contentTopicDist,goodTopic,goodTopicPerc,goodTopicDist,badTopic,badTopicPerc,badTopicDist
0,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,"스댕 용기 개 이쁘고 좋은데, 원가 너무 비싸서 내가 보기에는 가격이 높은 최대 ...",None,None,None,0,0.9935,"[(0, 0.9934807)]",1,0.9738,"[(1, 0.97384083)]"
1,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,NaN,4,0.8566,"[(0, 0.023957323), (1, 0.02386534), (2, 0.0239...",None,None,None,None,None,None
2,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,NaN,5,0.8567,"[(0, 0.023860294), (1, 0.023860116), (2, 0.023...",None,None,None,None,None,None
3,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,NaN,2,0.9547,"[(2, 0.954702)]",None,None,None,None,None,None
4,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,NaN,1,0.7851,"[(0, 0.035773713), (1, 0.7850679), (2, 0.03578...",None,None,None,None,None,None

In [348]:
drop_df[drop_df['badTopic'].notnull()]

,href,title,reviewNum,tag,brand,company,howToUse,ingredients,image,volume,...,commentBad,contentTopic,contentTopicPerc,contentTopicDist,goodTopic,goodTopicPerc,goodTopicDist,badTopic,badTopicPerc,badTopicDist
0,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,"스댕 용기 개 이쁘고 좋은데, 원가 너무 비싸서 내가 보기에는 가격이 높은 최대 ...",None,None,None,0,0.9935,"[(0, 0.9934807)]",1,0.9738,"[(1, 0.97384083)]"
501,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,"음 꼭찾아서 적으라면,, 가격? 탈모샴푸들 다들 비싸서 근데 뭐~ 다비싸니까요~ ...",None,None,None,4,0.987,"[(4, 0.987028)]",5,0.7119,"[(5, 0.71185887), (7, 0.24233761)]"
542,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,"스댕 용기 개 이쁘고 좋은데, 원가 너무 비싸서 내가 보기에는 가격이 높은 최대 ...",None,None,None,0,0.9935,"[(0, 0.9934807)]",1,0.9738,"[(1, 0.97384083)]"
573,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,가격이 조금 비싸긴 합니다. 그래도 새로운 기술이 적용되어 엄청난 쿨링감을 가지고...,None,None,None,4,0.9859,"[(4, 0.98594284)]",7,0.796,"[(0, 0.18455222), (7, 0.7959838)]"
781,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,특별히 없어요,None,None,None,5,0.9835,"[(5, 0.9834675)]",4,0.7035,"[(0, 0.037062634), (1, 0.037055537), (2, 0.037..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14073,https://daedamo.com/ingre/678?sca=탈모관련상품&overl...,\n 포미포미 맥주 샴푸,1.0,탈모샴푸,포미포미,(주)서울화장품,미온수로 모발 및 두피를 충분히 적신 후 적당량을 모발과 두피에 골고루 도포 후 2...,"정제수, 데실글루코사이드, 디소듐라우레스설포석시네이트, 포타슘코코일글리시네이트, 글...",https://daedamo.com/new/data/file/ingre/179434...,520ml,...,머리가 더빠짐 역시 약이 답이다,None,None,None,3,0.8946,"[(0, 0.021041287), (1, 0.021071786), (2, 0.021...",2,0.8729,"[(0, 0.015879462), (1, 0.015887208), (2, 0.872..."
14074,https://daedamo.com/ingre/2853?sca=탈모관련상품&over...,\n 상모단 샴푸,1.0,두피샴푸,어니스트쥬디,(주)서울화장품,물기가 있는 머리카락에 소량 펌핑하여 샴푸잉.,"인삼수, 흑미추출물, 검정콩추출물, 검은깨추출물, 소듐코코일글루타메이트, 데실글루코...",https://daedamo.com/new/data/file/ingre/373194...,250ml,...,한방샴푸라 그런지 한약재 냄새가 난다,None,None,None,2,0.8795,"[(0, 0.024082024), (1, 0.024048617), (2, 0.879...",0,0.8729,"[(0, 0.87293535), (1, 0.015883282), (2, 0.0158..."
14080,https://daedamo.com/ingre/598?sca=탈모관련상품&overl...,\n 하수오 허벌 에센셜 샴푸,1.0,탈모샴푸,피엘하수오,(주)서울화장품,모발이 젖은 상태에서 적당량을 덜어냅니다. 가볍게 마사지 하듯이 거품을 내어 감습니...,"암모늄라우레스설페이트, 편백수, 암모늄라우릴설페이트, 정제수, 메칠폴리실톡산에멀젼,...",https://daedamo.com/new/data/file/ingre/179434...,750ml,...,구하기 어려운 점? 하지만 도움은 안되는 것 같은 점..?,None,None,None,4,0.831,"[(0, 0.033727035), (1, 0.033743743), (2, 0.033...",4,0.9012,"[(0, 0.012351962), (1, 0.012351288), (2, 0.012..."
14081,https://daedamo.com/ingre/1281?sca=탈모관련상품&over...,\n 헤어캅 네츄럴 샴푸,2.0,두피샴푸,헤어캅,(주)서울화장품,미온수로 두피를 충분히 불려주세요. 샴푸 양은 500원 동전크기만큼으로 거품을 내어...,"어성초, 하수오, 고삼, 녹차, 오미자 등",https://daedamo.com/new/data/file/ingre/179434...,500g,...,아직까진 잘모르겠네요,None,None,None,2,0.8314,"[(0, 0.033679746), (1, 0.03383373), (2, 0.8314...",4,0.7777,"[(0, 0.027782874), (1, 0.027783778), (2, 0.027..."
14082,https://daedamo.com/ingre/1281?sca=탈모관련상품&over...,\n 헤어캅 네츄럴 샴푸,2.0,두피샴푸,헤어캅,(주)서울화장품,미온수로 두피를 충분히 불려주세요. 샴푸 양은 500원 동전크기만큼으로 거품을 내어...,"어성초, 하수오, 고삼, 녹차, 오미자 등",https://daedamo.com/new/data/file/ingre/179434...,500g,...,오래쓰니 두피장벽이 깨지더군요,None,None,None,4,0.8594,"[(0, 0.028076753), (1, 0.028225856), (2, 0.028...",6,0.8517,"[(0, 0.018532246), (1, 0.018537547), (2, 0.018..."

In [349]:
drop_df.to_csv('final_lda.csv',index=False,encoding='utf-8-sig',escapechar='\\')

In [304]:
drop_df.head()

,href,title,reviewNum,tag,brand,company,howToUse,ingredients,image,volume,...,priceScore,rebuyScore,commenter,commentDate,commentContent,commentGood,commentBad,contentTopic,contentTopicPerc,contentTopicDist
0,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,80%,100%,K2646350517,3달 전,NaN,"앞머리 모발이식 13년전에 하고는 프로스카 띄엄띄엄 먹었는데, 정수리 광탈 시작...","스댕 용기 개 이쁘고 좋은데, 원가 너무 비싸서 내가 보기에는 가격이 높은 최대 ...",None,None,None
1,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,NaN,NaN,a337*****,한 시간 전,탈모라 써봤는데 시원하고 좋아요,NaN,NaN,5,0.8567,None
2,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,NaN,NaN,suwo******,하루 전,머리감을때마다 시원하고좋아요,NaN,NaN,None,None,None
3,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,NaN,NaN,wall***,하루 전,전에 쿨샴푸를 한번썻는데 맘에들어서 다른색으로 하나 더 주문했습니다. 샘플 사은품...,NaN,NaN,None,None,None
4,https://daedamo.com/ingre/27320?sca=탈모관련상품&ove...,\n 블랙포레 두피 쿨&딥클린 탄산쿨링,962.0,탈모샴푸,블랙포레,애경산업,미온수로 모발 및 두피를 충분히 적시고 제품의 적당량을 취하여 두피 및 모발에 가볍...,"정제수,소듐C14-16올레핀설포네이트,소듐메틸코코일타우레이트,코카미도프로필베타인,글...",https://daedamo.com/new/data/file/ingre/210576...,500ml,...,NaN,NaN,zzzz****,2일 전,아주좋습니다좋아요~,NaN,NaN,None,None,None

good_topictable = make_topictable(good_model2,good_corpus)
# good_topictable
good_topictable.reset_index()
good_topictable.columns = ['문서 번호','가장 비중이 높은 토픽의 비중','각 토픽의 비중']
good_topictable
# topictable = topictable.reset_index()
# topictable.columns =